// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Trigger.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#ifndef FAST_DDS_GENERATED__STD_SRVS_SRV_TRIGGER_HPP
#define FAST_DDS_GENERATED__STD_SRVS_SRV_TRIGGER_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(TRIGGER_SOURCE)
#define TRIGGER_DllAPI __declspec( dllexport )
#else
#define TRIGGER_DllAPI __declspec( dllimport )
#endif // TRIGGER_SOURCE
#else
#define TRIGGER_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define TRIGGER_DllAPI
#endif // _WIN32

namespace std_srvs {

namespace srv {

/*!
 * @brief This class represents the structure Trigger_Request defined by the user in the IDL file.
 * @ingroup Trigger
 */
class Trigger_Request
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Trigger_Request()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Trigger_Request()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Trigger_Request that will be copied.
     */
    eProsima_user_DllExport Trigger_Request(
            const Trigger_Request& x)
    {
                    m_structure_needs_at_least_one_member = x.m_structure_needs_at_least_one_member;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Trigger_Request that will be copied.
     */
    eProsima_user_DllExport Trigger_Request(
            Trigger_Request&& x) noexcept
    {
        m_structure_needs_at_least_one_member = x.m_structure_needs_at_least_one_member;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Trigger_Request that will be copied.
     */
    eProsima_user_DllExport Trigger_Request& operator =(
            const Trigger_Request& x)
    {

                    m_structure_needs_at_least_one_member = x.m_structure_needs_at_least_one_member;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Trigger_Request that will be copied.
     */
    eProsima_user_DllExport Trigger_Request& operator =(
            Trigger_Request&& x) noexcept
    {

        m_structure_needs_at_least_one_member = x.m_structure_needs_at_least_one_member;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Trigger_Request object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Trigger_Request& x) const
    {
        return (m_structure_needs_at_least_one_member == x.m_structure_needs_at_least_one_member);
    }

    /*!
     * @brief Comparison operator.
     * @param x Trigger_Request object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Trigger_Request& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member structure_needs_at_least_one_member
     * @param _structure_needs_at_least_one_member New value for member structure_needs_at_least_one_member
     */
    eProsima_user_DllExport void structure_needs_at_least_one_member(
            uint8_t _structure_needs_at_least_one_member)
    {
        m_structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
    }

    /*!
     * @brief This function returns the value of member structure_needs_at_least_one_member
     * @return Value of member structure_needs_at_least_one_member
     */
    eProsima_user_DllExport uint8_t structure_needs_at_least_one_member() const
    {
        return m_structure_needs_at_least_one_member;
    }

    /*!
     * @brief This function returns a reference to member structure_needs_at_least_one_member
     * @return Reference to member structure_needs_at_least_one_member
     */
    eProsima_user_DllExport uint8_t& structure_needs_at_least_one_member()
    {
        return m_structure_needs_at_least_one_member;
    }



private:

    uint8_t m_structure_needs_at_least_one_member{0};

};
/*!
 * @brief This class represents the structure Trigger_Response defined by the user in the IDL file.
 * @ingroup Trigger
 */
class Trigger_Response
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Trigger_Response()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Trigger_Response()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Trigger_Response that will be copied.
     */
    eProsima_user_DllExport Trigger_Response(
            const Trigger_Response& x)
    {
                    m_success = x.m_success;

                    m_message = x.m_message;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Trigger_Response that will be copied.
     */
    eProsima_user_DllExport Trigger_Response(
            Trigger_Response&& x) noexcept
    {
        m_success = x.m_success;
        m_message = std::move(x.m_message);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Trigger_Response that will be copied.
     */
    eProsima_user_DllExport Trigger_Response& operator =(
            const Trigger_Response& x)
    {

                    m_success = x.m_success;

                    m_message = x.m_message;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Trigger_Response that will be copied.
     */
    eProsima_user_DllExport Trigger_Response& operator =(
            Trigger_Response&& x) noexcept
    {

        m_success = x.m_success;
        m_message = std::move(x.m_message);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Trigger_Response object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Trigger_Response& x) const
    {
        return (m_success == x.m_success &&
           m_message == x.m_message);
    }

    /*!
     * @brief Comparison operator.
     * @param x Trigger_Response object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Trigger_Response& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member success
     * @param _success New value for member success
     */
    eProsima_user_DllExport void success(
            bool _success)
    {
        m_success = _success;
    }

    /*!
     * @brief This function returns the value of member success
     * @return Value of member success
     */
    eProsima_user_DllExport bool success() const
    {
        return m_success;
    }

    /*!
     * @brief This function returns a reference to member success
     * @return Reference to member success
     */
    eProsima_user_DllExport bool& success()
    {
        return m_success;
    }


    /*!
     * @brief This function copies the value in member message
     * @param _message New value to be copied in member message
     */
    eProsima_user_DllExport void message(
            const std::string& _message)
    {
        m_message = _message;
    }

    /*!
     * @brief This function moves the value in member message
     * @param _message New value to be moved in member message
     */
    eProsima_user_DllExport void message(
            std::string&& _message)
    {
        m_message = std::move(_message);
    }

    /*!
     * @brief This function returns a constant reference to member message
     * @return Constant reference to member message
     */
    eProsima_user_DllExport const std::string& message() const
    {
        return m_message;
    }

    /*!
     * @brief This function returns a reference to member message
     * @return Reference to member message
     */
    eProsima_user_DllExport std::string& message()
    {
        return m_message;
    }



private:

    bool m_success{false};
    std::string m_message;

};

} // namespace srv

} // namespace std_srvs

#endif // _FAST_DDS_GENERATED_STD_SRVS_SRV_TRIGGER_HPP_


