// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SetParameters.i
 * This header file contains the SWIG interface of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

%module(moduleimport="if __import__('os').name == 'nt': import win32api; win32api.LoadLibrary('SetParameters.dll')\nif __package__ or '.' in __name__:\n    from . import _SetParametersWrapper\nelse:\n    import _SetParametersWrapper") SetParameters

// If using windows in debug, it would try to use python_d, which would not be found.
%begin %{
#ifdef _MSC_VER
#define SWIG_PYTHON_INTERPRETER_NO_DEBUG
#endif
#include <exception>
%}

// SWIG helper modules
%include "stdint.i"
%include "std_array.i"
%include "std_map.i"
%include "std_string.i"
%include "std_vector.i"
%include "typemaps.i"

// Assignemt operators are ignored, as there is no such thing in Python.
// Trying to export them issues a warning
%ignore *::operator=;

// Macro declarations
// Any macro used on the Fast DDS header files will give an error if it is not redefined here
#define FASTDDS_EXPORTED_API
#define eProsima_user_DllExport

%include "rcl_interfaces/msg/Parameter.i"
%include "rcl_interfaces/msg/SetParametersResult.i"

%{
#include "SetParameters.hpp"
#include <fastdds/dds/core/LoanableSequence.hpp>
%}

%include <fastcdr/config.h>
%import(module="fastdds") "fastdds/dds/core/LoanableCollection.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableTypedCollection.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableSequence.hpp"

%define %traits_penumn(Type...)
  %fragment(SWIG_Traits_frag(Type),"header",
        fragment="StdTraits") {
namespace swig {
  template <> struct traits< Type > {
    typedef value_category category;
    static const char* type_name() { return  #Type; }
  };
}
}
%enddef

////////////////////////////////////////////////////////
// Binding for class rcl_interfaces::srv::SetParameters_Request
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore rcl_interfaces::srv::SetParameters_Request::SetParameters_Request(rcl_interfaces::srv::SetParameters_Request&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore rcl_interfaces::srv::SetParameters_Request::parameters(std::vector<rcl_interfaces::msg::Parameter>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore rcl_interfaces::srv::SetParameters_Request::parameters() const;
%template(Parameter_vector) std::vector<rcl_interfaces::msg::Parameter>;


%template(_SetParameters_RequestSeq) eprosima::fastdds::dds::LoanableTypedCollection<rcl_interfaces::srv::SetParameters_Request, std::false_type>;
%template(SetParameters_RequestSeq) eprosima::fastdds::dds::LoanableSequence<rcl_interfaces::srv::SetParameters_Request, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<rcl_interfaces::srv::SetParameters_Request, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const rcl_interfaces::srv::SetParameters_Request& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class rcl_interfaces::srv::SetParameters_Response
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore rcl_interfaces::srv::SetParameters_Response::SetParameters_Response(rcl_interfaces::srv::SetParameters_Response&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore rcl_interfaces::srv::SetParameters_Response::results(std::vector<rcl_interfaces::msg::SetParametersResult>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore rcl_interfaces::srv::SetParameters_Response::results() const;
%template(SetParametersResult_vector) std::vector<rcl_interfaces::msg::SetParametersResult>;


%template(_SetParameters_ResponseSeq) eprosima::fastdds::dds::LoanableTypedCollection<rcl_interfaces::srv::SetParameters_Response, std::false_type>;
%template(SetParameters_ResponseSeq) eprosima::fastdds::dds::LoanableSequence<rcl_interfaces::srv::SetParameters_Response, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<rcl_interfaces::srv::SetParameters_Response, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const rcl_interfaces::srv::SetParameters_Response& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}


// Include the class interfaces
%include "SetParameters.hpp"

// Include the corresponding TopicDataType
%include "SetParametersPubSubTypes.i"

