// Copyright 2025 Provizio Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "std_msgs/msg/Header.idl"
#include "provizio/msg/radar_range.idl"

module provizio {
  module srv {
    struct set_radar_range_Request {
      std_msgs::msg::Header header;
      
      @verbatim(language="comment", text="Optional, specify to make sure only the desired radar gets the range changed, ignoring header.frame_id")
      string serial_number;
      provizio::msg::radar_range target_range;
    };

    struct set_radar_range_Response {
      std_msgs::msg::Header header;
      
      boolean success;
      string error_message;

      string serial_number;
      sequence<provizio::msg::radar_range> supported_ranges;
      provizio::msg::radar_range current_range;
    };
  };
};
