// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file AccelStampedTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#include "AccelStampedTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "AccelStamped.hpp"

#include "std_msgs/msg/Header.hpp"
#include "geometry_msgs/msg/Accel.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace geometry_msgs {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_AccelStamped_type_identifier(
        TypeIdentifierPair& type_ids_AccelStamped)
{

    ReturnCode_t return_code_AccelStamped {eprosima::fastdds::dds::RETCODE_OK};
    return_code_AccelStamped =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "geometry_msgs::msg::dds_::AccelStamped_", type_ids_AccelStamped);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_AccelStamped)
    {
        StructTypeFlag struct_flags_AccelStamped = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_AccelStamped = "geometry_msgs::msg::dds_::AccelStamped_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_AccelStamped;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_AccelStamped;
        CompleteTypeDetail detail_AccelStamped = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_AccelStamped, ann_custom_AccelStamped, type_name_AccelStamped.to_string());
        CompleteStructHeader header_AccelStamped;
        header_AccelStamped = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_AccelStamped);
        CompleteStructMemberSeq member_seq_AccelStamped;
        {
            TypeIdentifierPair type_ids_header;
            ReturnCode_t return_code_header {eprosima::fastdds::dds::RETCODE_OK};
            return_code_header =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "std_msgs::msg::dds_::Header_", type_ids_header);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_header)
            {
                ::std_msgs::msg::register_Header_type_identifier(type_ids_header);
            }
            StructMemberFlag member_flags_header = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_header = 0x00000000;
            bool common_header_ec {false};
            CommonStructMember common_header {TypeObjectUtils::build_common_struct_member(member_id_header, member_flags_header, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_header, common_header_ec))};
            if (!common_header_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure header member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_header = "header";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_header;
            ann_custom_AccelStamped.reset();
            CompleteMemberDetail detail_header = TypeObjectUtils::build_complete_member_detail(name_header, member_ann_builtin_header, ann_custom_AccelStamped);
            CompleteStructMember member_header = TypeObjectUtils::build_complete_struct_member(common_header, detail_header);
            TypeObjectUtils::add_complete_struct_member(member_seq_AccelStamped, member_header);
        }
        {
            TypeIdentifierPair type_ids_accel;
            ReturnCode_t return_code_accel {eprosima::fastdds::dds::RETCODE_OK};
            return_code_accel =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "geometry_msgs::msg::dds_::Accel_", type_ids_accel);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_accel)
            {
                ::geometry_msgs::msg::register_Accel_type_identifier(type_ids_accel);
            }
            StructMemberFlag member_flags_accel = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_accel = 0x00000001;
            bool common_accel_ec {false};
            CommonStructMember common_accel {TypeObjectUtils::build_common_struct_member(member_id_accel, member_flags_accel, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_accel, common_accel_ec))};
            if (!common_accel_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure accel member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_accel = "accel";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_accel;
            ann_custom_AccelStamped.reset();
            CompleteMemberDetail detail_accel = TypeObjectUtils::build_complete_member_detail(name_accel, member_ann_builtin_accel, ann_custom_AccelStamped);
            CompleteStructMember member_accel = TypeObjectUtils::build_complete_struct_member(common_accel, detail_accel);
            TypeObjectUtils::add_complete_struct_member(member_seq_AccelStamped, member_accel);
        }
        CompleteStructType struct_type_AccelStamped = TypeObjectUtils::build_complete_struct_type(struct_flags_AccelStamped, header_AccelStamped, member_seq_AccelStamped);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_AccelStamped, type_name_AccelStamped.to_string(), type_ids_AccelStamped))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "geometry_msgs::msg::AccelStamped already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace msg

} // namespace geometry_msgs

