// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Polygon.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#ifndef FAST_DDS_GENERATED__GEOMETRY_MSGS_MSG_POLYGON_HPP
#define FAST_DDS_GENERATED__GEOMETRY_MSGS_MSG_POLYGON_HPP

#include <cstdint>
#include <utility>
#include <vector>

#include "Point32.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(POLYGON_SOURCE)
#define POLYGON_DllAPI __declspec( dllexport )
#else
#define POLYGON_DllAPI __declspec( dllimport )
#endif // POLYGON_SOURCE
#else
#define POLYGON_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define POLYGON_DllAPI
#endif // _WIN32

namespace geometry_msgs {

namespace msg {

/*!
 * @brief This class represents the structure Polygon defined by the user in the IDL file.
 * @ingroup Polygon
 */
class Polygon
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Polygon()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Polygon()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Polygon that will be copied.
     */
    eProsima_user_DllExport Polygon(
            const Polygon& x)
    {
                    m_points = x.m_points;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Polygon that will be copied.
     */
    eProsima_user_DllExport Polygon(
            Polygon&& x) noexcept
    {
        m_points = std::move(x.m_points);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Polygon that will be copied.
     */
    eProsima_user_DllExport Polygon& operator =(
            const Polygon& x)
    {

                    m_points = x.m_points;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Polygon that will be copied.
     */
    eProsima_user_DllExport Polygon& operator =(
            Polygon&& x) noexcept
    {

        m_points = std::move(x.m_points);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Polygon object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Polygon& x) const
    {
        return (m_points == x.m_points);
    }

    /*!
     * @brief Comparison operator.
     * @param x Polygon object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Polygon& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member points
     * @param _points New value to be copied in member points
     */
    eProsima_user_DllExport void points(
            const std::vector<Point32>& _points)
    {
        m_points = _points;
    }

    /*!
     * @brief This function moves the value in member points
     * @param _points New value to be moved in member points
     */
    eProsima_user_DllExport void points(
            std::vector<Point32>&& _points)
    {
        m_points = std::move(_points);
    }

    /*!
     * @brief This function returns a constant reference to member points
     * @return Constant reference to member points
     */
    eProsima_user_DllExport const std::vector<Point32>& points() const
    {
        return m_points;
    }

    /*!
     * @brief This function returns a reference to member points
     * @return Reference to member points
     */
    eProsima_user_DllExport std::vector<Point32>& points()
    {
        return m_points;
    }



private:

    std::vector<Point32> m_points;

};

} // namespace msg

} // namespace geometry_msgs

#endif // _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_POLYGON_HPP_


