// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file PoseStamped.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#ifndef FAST_DDS_GENERATED__GEOMETRY_MSGS_MSG_POSESTAMPED_HPP
#define FAST_DDS_GENERATED__GEOMETRY_MSGS_MSG_POSESTAMPED_HPP

#include <cstdint>
#include <utility>
#include "std_msgs/msg/Header.hpp"
#include "geometry_msgs/msg/Pose.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(POSESTAMPED_SOURCE)
#define POSESTAMPED_DllAPI __declspec( dllexport )
#else
#define POSESTAMPED_DllAPI __declspec( dllimport )
#endif // POSESTAMPED_SOURCE
#else
#define POSESTAMPED_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define POSESTAMPED_DllAPI
#endif // _WIN32

namespace geometry_msgs {

namespace msg {

/*!
 * @brief This class represents the structure PoseStamped defined by the user in the IDL file.
 * @ingroup PoseStamped
 */
class PoseStamped
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport PoseStamped()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~PoseStamped()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object PoseStamped that will be copied.
     */
    eProsima_user_DllExport PoseStamped(
            const PoseStamped& x)
    {
                    m_header = x.m_header;

                    m_pose = x.m_pose;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object PoseStamped that will be copied.
     */
    eProsima_user_DllExport PoseStamped(
            PoseStamped&& x) noexcept
    {
        m_header = std::move(x.m_header);
        m_pose = std::move(x.m_pose);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object PoseStamped that will be copied.
     */
    eProsima_user_DllExport PoseStamped& operator =(
            const PoseStamped& x)
    {

                    m_header = x.m_header;

                    m_pose = x.m_pose;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object PoseStamped that will be copied.
     */
    eProsima_user_DllExport PoseStamped& operator =(
            PoseStamped&& x) noexcept
    {

        m_header = std::move(x.m_header);
        m_pose = std::move(x.m_pose);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x PoseStamped object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const PoseStamped& x) const
    {
        return (m_header == x.m_header &&
           m_pose == x.m_pose);
    }

    /*!
     * @brief Comparison operator.
     * @param x PoseStamped object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const PoseStamped& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member header
     * @param _header New value to be copied in member header
     */
    eProsima_user_DllExport void header(
            const std_msgs::msg::Header& _header)
    {
        m_header = _header;
    }

    /*!
     * @brief This function moves the value in member header
     * @param _header New value to be moved in member header
     */
    eProsima_user_DllExport void header(
            std_msgs::msg::Header&& _header)
    {
        m_header = std::move(_header);
    }

    /*!
     * @brief This function returns a constant reference to member header
     * @return Constant reference to member header
     */
    eProsima_user_DllExport const std_msgs::msg::Header& header() const
    {
        return m_header;
    }

    /*!
     * @brief This function returns a reference to member header
     * @return Reference to member header
     */
    eProsima_user_DllExport std_msgs::msg::Header& header()
    {
        return m_header;
    }


    /*!
     * @brief This function copies the value in member pose
     * @param _pose New value to be copied in member pose
     */
    eProsima_user_DllExport void pose(
            const Pose& _pose)
    {
        m_pose = _pose;
    }

    /*!
     * @brief This function moves the value in member pose
     * @param _pose New value to be moved in member pose
     */
    eProsima_user_DllExport void pose(
            Pose&& _pose)
    {
        m_pose = std::move(_pose);
    }

    /*!
     * @brief This function returns a constant reference to member pose
     * @return Constant reference to member pose
     */
    eProsima_user_DllExport const Pose& pose() const
    {
        return m_pose;
    }

    /*!
     * @brief This function returns a reference to member pose
     * @return Reference to member pose
     */
    eProsima_user_DllExport Pose& pose()
    {
        return m_pose;
    }



private:

    std_msgs::msg::Header m_header;
    Pose m_pose;

};

} // namespace msg

} // namespace geometry_msgs

#endif // _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_POSESTAMPED_HPP_


