// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file PoseArray.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#ifndef FAST_DDS_GENERATED__GEOMETRY_MSGS_MSG_POSEARRAY_HPP
#define FAST_DDS_GENERATED__GEOMETRY_MSGS_MSG_POSEARRAY_HPP

#include <cstdint>
#include <utility>
#include <vector>

#include "std_msgs/msg/Header.hpp"
#include "geometry_msgs/msg/Pose.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(POSEARRAY_SOURCE)
#define POSEARRAY_DllAPI __declspec( dllexport )
#else
#define POSEARRAY_DllAPI __declspec( dllimport )
#endif // POSEARRAY_SOURCE
#else
#define POSEARRAY_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define POSEARRAY_DllAPI
#endif // _WIN32

namespace geometry_msgs {

namespace msg {

/*!
 * @brief This class represents the structure PoseArray defined by the user in the IDL file.
 * @ingroup PoseArray
 */
class PoseArray
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport PoseArray()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~PoseArray()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object PoseArray that will be copied.
     */
    eProsima_user_DllExport PoseArray(
            const PoseArray& x)
    {
                    m_header = x.m_header;

                    m_poses = x.m_poses;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object PoseArray that will be copied.
     */
    eProsima_user_DllExport PoseArray(
            PoseArray&& x) noexcept
    {
        m_header = std::move(x.m_header);
        m_poses = std::move(x.m_poses);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object PoseArray that will be copied.
     */
    eProsima_user_DllExport PoseArray& operator =(
            const PoseArray& x)
    {

                    m_header = x.m_header;

                    m_poses = x.m_poses;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object PoseArray that will be copied.
     */
    eProsima_user_DllExport PoseArray& operator =(
            PoseArray&& x) noexcept
    {

        m_header = std::move(x.m_header);
        m_poses = std::move(x.m_poses);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x PoseArray object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const PoseArray& x) const
    {
        return (m_header == x.m_header &&
           m_poses == x.m_poses);
    }

    /*!
     * @brief Comparison operator.
     * @param x PoseArray object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const PoseArray& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member header
     * @param _header New value to be copied in member header
     */
    eProsima_user_DllExport void header(
            const std_msgs::msg::Header& _header)
    {
        m_header = _header;
    }

    /*!
     * @brief This function moves the value in member header
     * @param _header New value to be moved in member header
     */
    eProsima_user_DllExport void header(
            std_msgs::msg::Header&& _header)
    {
        m_header = std::move(_header);
    }

    /*!
     * @brief This function returns a constant reference to member header
     * @return Constant reference to member header
     */
    eProsima_user_DllExport const std_msgs::msg::Header& header() const
    {
        return m_header;
    }

    /*!
     * @brief This function returns a reference to member header
     * @return Reference to member header
     */
    eProsima_user_DllExport std_msgs::msg::Header& header()
    {
        return m_header;
    }


    /*!
     * @brief This function copies the value in member poses
     * @param _poses New value to be copied in member poses
     */
    eProsima_user_DllExport void poses(
            const std::vector<Pose>& _poses)
    {
        m_poses = _poses;
    }

    /*!
     * @brief This function moves the value in member poses
     * @param _poses New value to be moved in member poses
     */
    eProsima_user_DllExport void poses(
            std::vector<Pose>&& _poses)
    {
        m_poses = std::move(_poses);
    }

    /*!
     * @brief This function returns a constant reference to member poses
     * @return Constant reference to member poses
     */
    eProsima_user_DllExport const std::vector<Pose>& poses() const
    {
        return m_poses;
    }

    /*!
     * @brief This function returns a reference to member poses
     * @return Reference to member poses
     */
    eProsima_user_DllExport std::vector<Pose>& poses()
    {
        return m_poses;
    }



private:

    std_msgs::msg::Header m_header;
    std::vector<Pose> m_poses;

};

} // namespace msg

} // namespace geometry_msgs

#endif // _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_POSEARRAY_HPP_


