// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TransformTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#include "TransformTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "Transform.hpp"

#include "Quaternion.hpp"
#include "Vector3.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace geometry_msgs {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Transform_type_identifier(
        TypeIdentifierPair& type_ids_Transform)
{

    ReturnCode_t return_code_Transform {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Transform =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "geometry_msgs::msg::dds_::Transform_", type_ids_Transform);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Transform)
    {
        StructTypeFlag struct_flags_Transform = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_Transform = "geometry_msgs::msg::dds_::Transform_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Transform;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Transform;
        CompleteTypeDetail detail_Transform = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Transform, ann_custom_Transform, type_name_Transform.to_string());
        CompleteStructHeader header_Transform;
        header_Transform = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Transform);
        CompleteStructMemberSeq member_seq_Transform;
        {
            TypeIdentifierPair type_ids_translation;
            ReturnCode_t return_code_translation {eprosima::fastdds::dds::RETCODE_OK};
            return_code_translation =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "geometry_msgs::msg::dds_::Vector3_", type_ids_translation);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_translation)
            {
                ::geometry_msgs::msg::register_Vector3_type_identifier(type_ids_translation);
            }
            StructMemberFlag member_flags_translation = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_translation = 0x00000000;
            bool common_translation_ec {false};
            CommonStructMember common_translation {TypeObjectUtils::build_common_struct_member(member_id_translation, member_flags_translation, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_translation, common_translation_ec))};
            if (!common_translation_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure translation member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_translation = "translation";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_translation;
            ann_custom_Transform.reset();
            CompleteMemberDetail detail_translation = TypeObjectUtils::build_complete_member_detail(name_translation, member_ann_builtin_translation, ann_custom_Transform);
            CompleteStructMember member_translation = TypeObjectUtils::build_complete_struct_member(common_translation, detail_translation);
            TypeObjectUtils::add_complete_struct_member(member_seq_Transform, member_translation);
        }
        {
            TypeIdentifierPair type_ids_rotation;
            ReturnCode_t return_code_rotation {eprosima::fastdds::dds::RETCODE_OK};
            return_code_rotation =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "geometry_msgs::msg::dds_::Quaternion_", type_ids_rotation);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_rotation)
            {
                ::geometry_msgs::msg::register_Quaternion_type_identifier(type_ids_rotation);
            }
            StructMemberFlag member_flags_rotation = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_rotation = 0x00000001;
            bool common_rotation_ec {false};
            CommonStructMember common_rotation {TypeObjectUtils::build_common_struct_member(member_id_rotation, member_flags_rotation, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_rotation, common_rotation_ec))};
            if (!common_rotation_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure rotation member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_rotation = "rotation";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_rotation;
            ann_custom_Transform.reset();
            CompleteMemberDetail detail_rotation = TypeObjectUtils::build_complete_member_detail(name_rotation, member_ann_builtin_rotation, ann_custom_Transform);
            CompleteStructMember member_rotation = TypeObjectUtils::build_complete_struct_member(common_rotation, detail_rotation);
            TypeObjectUtils::add_complete_struct_member(member_seq_Transform, member_rotation);
        }
        CompleteStructType struct_type_Transform = TypeObjectUtils::build_complete_struct_type(struct_flags_Transform, header_Transform, member_seq_Transform);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Transform, type_name_Transform.to_string(), type_ids_Transform))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "geometry_msgs::msg::Transform already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace msg

} // namespace geometry_msgs

