// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Transform.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#ifndef FAST_DDS_GENERATED__GEOMETRY_MSGS_MSG_TRANSFORM_HPP
#define FAST_DDS_GENERATED__GEOMETRY_MSGS_MSG_TRANSFORM_HPP

#include <cstdint>
#include <utility>
#include "Quaternion.hpp"
#include "Vector3.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(TRANSFORM_SOURCE)
#define TRANSFORM_DllAPI __declspec( dllexport )
#else
#define TRANSFORM_DllAPI __declspec( dllimport )
#endif // TRANSFORM_SOURCE
#else
#define TRANSFORM_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define TRANSFORM_DllAPI
#endif // _WIN32

namespace geometry_msgs {

namespace msg {

/*!
 * @brief This class represents the structure Transform defined by the user in the IDL file.
 * @ingroup Transform
 */
class Transform
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Transform()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Transform()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Transform that will be copied.
     */
    eProsima_user_DllExport Transform(
            const Transform& x)
    {
                    m_translation = x.m_translation;

                    m_rotation = x.m_rotation;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Transform that will be copied.
     */
    eProsima_user_DllExport Transform(
            Transform&& x) noexcept
    {
        m_translation = std::move(x.m_translation);
        m_rotation = std::move(x.m_rotation);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Transform that will be copied.
     */
    eProsima_user_DllExport Transform& operator =(
            const Transform& x)
    {

                    m_translation = x.m_translation;

                    m_rotation = x.m_rotation;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Transform that will be copied.
     */
    eProsima_user_DllExport Transform& operator =(
            Transform&& x) noexcept
    {

        m_translation = std::move(x.m_translation);
        m_rotation = std::move(x.m_rotation);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Transform object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Transform& x) const
    {
        return (m_translation == x.m_translation &&
           m_rotation == x.m_rotation);
    }

    /*!
     * @brief Comparison operator.
     * @param x Transform object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Transform& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member translation
     * @param _translation New value to be copied in member translation
     */
    eProsima_user_DllExport void translation(
            const Vector3& _translation)
    {
        m_translation = _translation;
    }

    /*!
     * @brief This function moves the value in member translation
     * @param _translation New value to be moved in member translation
     */
    eProsima_user_DllExport void translation(
            Vector3&& _translation)
    {
        m_translation = std::move(_translation);
    }

    /*!
     * @brief This function returns a constant reference to member translation
     * @return Constant reference to member translation
     */
    eProsima_user_DllExport const Vector3& translation() const
    {
        return m_translation;
    }

    /*!
     * @brief This function returns a reference to member translation
     * @return Reference to member translation
     */
    eProsima_user_DllExport Vector3& translation()
    {
        return m_translation;
    }


    /*!
     * @brief This function copies the value in member rotation
     * @param _rotation New value to be copied in member rotation
     */
    eProsima_user_DllExport void rotation(
            const Quaternion& _rotation)
    {
        m_rotation = _rotation;
    }

    /*!
     * @brief This function moves the value in member rotation
     * @param _rotation New value to be moved in member rotation
     */
    eProsima_user_DllExport void rotation(
            Quaternion&& _rotation)
    {
        m_rotation = std::move(_rotation);
    }

    /*!
     * @brief This function returns a constant reference to member rotation
     * @return Constant reference to member rotation
     */
    eProsima_user_DllExport const Quaternion& rotation() const
    {
        return m_rotation;
    }

    /*!
     * @brief This function returns a reference to member rotation
     * @return Reference to member rotation
     */
    eProsima_user_DllExport Quaternion& rotation()
    {
        return m_rotation;
    }



private:

    Vector3 m_translation;
    Quaternion m_rotation;

};

} // namespace msg

} // namespace geometry_msgs

#endif // _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_TRANSFORM_HPP_


