// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ParameterValue.i
 * This header file contains the SWIG interface of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

%module(moduleimport="if __import__('os').name == 'nt': import win32api; win32api.LoadLibrary('ParameterValue.dll')\nif __package__ or '.' in __name__:\n    from . import _ParameterValueWrapper\nelse:\n    import _ParameterValueWrapper") ParameterValue

// If using windows in debug, it would try to use python_d, which would not be found.
%begin %{
#ifdef _MSC_VER
#define SWIG_PYTHON_INTERPRETER_NO_DEBUG
#endif
#include <exception>
%}

// SWIG helper modules
%include "stdint.i"
%include "std_array.i"
%include "std_map.i"
%include "std_string.i"
%include "std_vector.i"
%include "typemaps.i"

// Assignemt operators are ignored, as there is no such thing in Python.
// Trying to export them issues a warning
%ignore *::operator=;

// Macro declarations
// Any macro used on the Fast DDS header files will give an error if it is not redefined here
#define FASTDDS_EXPORTED_API
#define eProsima_user_DllExport


%{
#include "ParameterValue.hpp"
#include <fastdds/dds/core/LoanableSequence.hpp>
%}

%include <fastcdr/config.h>
%import(module="fastdds") "fastcdr/cdr/fixed_size_string.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableCollection.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableTypedCollection.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableSequence.hpp"

%define %traits_penumn(Type...)
  %fragment(SWIG_Traits_frag(Type),"header",
        fragment="StdTraits") {
namespace swig {
  template <> struct traits< Type > {
    typedef value_category category;
    static const char* type_name() { return  #Type; }
  };
}
}
%enddef

////////////////////////////////////////////////////////
// Binding for class rcl_interfaces::msg::ParameterValue
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore rcl_interfaces::msg::ParameterValue::ParameterValue(rcl_interfaces::msg::ParameterValue&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore rcl_interfaces::msg::ParameterValue::type(uint8_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore rcl_interfaces::msg::ParameterValue::type();
%rename("%s") rcl_interfaces::msg::ParameterValue::type() const;



%ignore rcl_interfaces::msg::ParameterValue::bool_value(bool&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore rcl_interfaces::msg::ParameterValue::bool_value();
%rename("%s") rcl_interfaces::msg::ParameterValue::bool_value() const;



%ignore rcl_interfaces::msg::ParameterValue::integer_value(int64_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore rcl_interfaces::msg::ParameterValue::integer_value();
%rename("%s") rcl_interfaces::msg::ParameterValue::integer_value() const;



%ignore rcl_interfaces::msg::ParameterValue::double_value(double&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore rcl_interfaces::msg::ParameterValue::double_value();
%rename("%s") rcl_interfaces::msg::ParameterValue::double_value() const;



%ignore rcl_interfaces::msg::ParameterValue::string_value(std::string&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore rcl_interfaces::msg::ParameterValue::string_value();
%rename("%s") rcl_interfaces::msg::ParameterValue::string_value() const;



%ignore rcl_interfaces::msg::ParameterValue::byte_array_value(std::vector<uint8_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore rcl_interfaces::msg::ParameterValue::byte_array_value() const;
%extend std::vector<uint8_t>
{
    const uint8_t* get_buffer() const
    {
        return self->data();
    }
}

%template(uint8_t_vector) std::vector<uint8_t>;


%ignore rcl_interfaces::msg::ParameterValue::bool_array_value(std::vector<bool>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore rcl_interfaces::msg::ParameterValue::bool_array_value() const;
%template(bool_vector) std::vector<bool>;


%ignore rcl_interfaces::msg::ParameterValue::integer_array_value(std::vector<int64_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore rcl_interfaces::msg::ParameterValue::integer_array_value() const;
%extend std::vector<int64_t>
{
    const int64_t* get_buffer() const
    {
        return self->data();
    }
}

%template(int64_t_vector) std::vector<int64_t>;


%ignore rcl_interfaces::msg::ParameterValue::double_array_value(std::vector<double>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore rcl_interfaces::msg::ParameterValue::double_array_value() const;
%extend std::vector<double>
{
    const double* get_buffer() const
    {
        return self->data();
    }
}

%template(double_vector) std::vector<double>;


%ignore rcl_interfaces::msg::ParameterValue::string_array_value(std::vector<std::string>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore rcl_interfaces::msg::ParameterValue::string_array_value() const;
%template(string_vector) std::vector<std::string>;


%template(_ParameterValueSeq) eprosima::fastdds::dds::LoanableTypedCollection<rcl_interfaces::msg::ParameterValue, std::false_type>;
%template(ParameterValueSeq) eprosima::fastdds::dds::LoanableSequence<rcl_interfaces::msg::ParameterValue, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<rcl_interfaces::msg::ParameterValue, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const rcl_interfaces::msg::ParameterValue& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}


// Include the class interfaces
%include "ParameterValue.hpp"

// Include the corresponding TopicDataType
%include "ParameterValuePubSubTypes.i"

