// Copyright 2023 Provizio Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "std_msgs/msg/Header.idl"

module provizio {
  module msg {
    struct camera_intrinsics_precise_model
    {
        float camera_matrix[9];
        float distortion_coefficients[8];
    };

    struct camera_intrinsics_perspective
    {
        float hfov;
        camera_intrinsics_precise_model precise_model;
    };

    struct camera_intrinsics_orthographic
    {
        float width;
        float height;
    };

    struct camera_intrinsics {
      std_msgs::msg::Header header;
      camera_intrinsics_perspective perspective;
      camera_intrinsics_orthographic orthographic;
    };
  };
};
