// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file GetPlanTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#include "GetPlanTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "GetPlan.hpp"

#include "geometry_msgs/msg/PoseStamped.hpp"
#include "nav_msgs/msg/Path.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace nav_msgs {
namespace srv {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_GetPlan_Request_type_identifier(
        TypeIdentifierPair& type_ids_GetPlan_Request)
{

    ReturnCode_t return_code_GetPlan_Request {eprosima::fastdds::dds::RETCODE_OK};
    return_code_GetPlan_Request =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "nav_msgs::srv::dds_::GetPlan_Request_", type_ids_GetPlan_Request);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_GetPlan_Request)
    {
        StructTypeFlag struct_flags_GetPlan_Request = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_GetPlan_Request = "nav_msgs::srv::dds_::GetPlan_Request_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_GetPlan_Request;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_GetPlan_Request;
        CompleteTypeDetail detail_GetPlan_Request = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_GetPlan_Request, ann_custom_GetPlan_Request, type_name_GetPlan_Request.to_string());
        CompleteStructHeader header_GetPlan_Request;
        header_GetPlan_Request = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_GetPlan_Request);
        CompleteStructMemberSeq member_seq_GetPlan_Request;
        {
            TypeIdentifierPair type_ids_start;
            ReturnCode_t return_code_start {eprosima::fastdds::dds::RETCODE_OK};
            return_code_start =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "geometry_msgs::msg::dds_::PoseStamped_", type_ids_start);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_start)
            {
                ::geometry_msgs::msg::register_PoseStamped_type_identifier(type_ids_start);
            }
            StructMemberFlag member_flags_start = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_start = 0x00000000;
            bool common_start_ec {false};
            CommonStructMember common_start {TypeObjectUtils::build_common_struct_member(member_id_start, member_flags_start, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_start, common_start_ec))};
            if (!common_start_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure start member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_start = "start";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_start;
            ann_custom_GetPlan_Request.reset();
            CompleteMemberDetail detail_start = TypeObjectUtils::build_complete_member_detail(name_start, member_ann_builtin_start, ann_custom_GetPlan_Request);
            CompleteStructMember member_start = TypeObjectUtils::build_complete_struct_member(common_start, detail_start);
            TypeObjectUtils::add_complete_struct_member(member_seq_GetPlan_Request, member_start);
        }
        {
            TypeIdentifierPair type_ids_goal;
            ReturnCode_t return_code_goal {eprosima::fastdds::dds::RETCODE_OK};
            return_code_goal =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "geometry_msgs::msg::dds_::PoseStamped_", type_ids_goal);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_goal)
            {
                ::geometry_msgs::msg::register_PoseStamped_type_identifier(type_ids_goal);
            }
            StructMemberFlag member_flags_goal = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_goal = 0x00000001;
            bool common_goal_ec {false};
            CommonStructMember common_goal {TypeObjectUtils::build_common_struct_member(member_id_goal, member_flags_goal, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_goal, common_goal_ec))};
            if (!common_goal_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure goal member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_goal = "goal";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_goal;
            ann_custom_GetPlan_Request.reset();
            CompleteMemberDetail detail_goal = TypeObjectUtils::build_complete_member_detail(name_goal, member_ann_builtin_goal, ann_custom_GetPlan_Request);
            CompleteStructMember member_goal = TypeObjectUtils::build_complete_struct_member(common_goal, detail_goal);
            TypeObjectUtils::add_complete_struct_member(member_seq_GetPlan_Request, member_goal);
        }
        {
            TypeIdentifierPair type_ids_tolerance;
            ReturnCode_t return_code_tolerance {eprosima::fastdds::dds::RETCODE_OK};
            return_code_tolerance =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_tolerance);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_tolerance)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "tolerance Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_tolerance = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_tolerance = 0x00000002;
            bool common_tolerance_ec {false};
            CommonStructMember common_tolerance {TypeObjectUtils::build_common_struct_member(member_id_tolerance, member_flags_tolerance, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_tolerance, common_tolerance_ec))};
            if (!common_tolerance_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure tolerance member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_tolerance = "tolerance";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_tolerance;
            ann_custom_GetPlan_Request.reset();
            CompleteMemberDetail detail_tolerance = TypeObjectUtils::build_complete_member_detail(name_tolerance, member_ann_builtin_tolerance, ann_custom_GetPlan_Request);
            CompleteStructMember member_tolerance = TypeObjectUtils::build_complete_struct_member(common_tolerance, detail_tolerance);
            TypeObjectUtils::add_complete_struct_member(member_seq_GetPlan_Request, member_tolerance);
        }
        CompleteStructType struct_type_GetPlan_Request = TypeObjectUtils::build_complete_struct_type(struct_flags_GetPlan_Request, header_GetPlan_Request, member_seq_GetPlan_Request);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_GetPlan_Request, type_name_GetPlan_Request.to_string(), type_ids_GetPlan_Request))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "nav_msgs::srv::GetPlan_Request already registered in TypeObjectRegistry for a different type.");
        }
    }
}// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_GetPlan_Response_type_identifier(
        TypeIdentifierPair& type_ids_GetPlan_Response)
{

    ReturnCode_t return_code_GetPlan_Response {eprosima::fastdds::dds::RETCODE_OK};
    return_code_GetPlan_Response =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "nav_msgs::srv::dds_::GetPlan_Response_", type_ids_GetPlan_Response);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_GetPlan_Response)
    {
        StructTypeFlag struct_flags_GetPlan_Response = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_GetPlan_Response = "nav_msgs::srv::dds_::GetPlan_Response_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_GetPlan_Response;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_GetPlan_Response;
        CompleteTypeDetail detail_GetPlan_Response = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_GetPlan_Response, ann_custom_GetPlan_Response, type_name_GetPlan_Response.to_string());
        CompleteStructHeader header_GetPlan_Response;
        header_GetPlan_Response = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_GetPlan_Response);
        CompleteStructMemberSeq member_seq_GetPlan_Response;
        {
            TypeIdentifierPair type_ids_plan;
            ReturnCode_t return_code_plan {eprosima::fastdds::dds::RETCODE_OK};
            return_code_plan =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "nav_msgs::msg::dds_::Path_", type_ids_plan);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_plan)
            {
                ::nav_msgs::msg::register_Path_type_identifier(type_ids_plan);
            }
            StructMemberFlag member_flags_plan = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_plan = 0x00000000;
            bool common_plan_ec {false};
            CommonStructMember common_plan {TypeObjectUtils::build_common_struct_member(member_id_plan, member_flags_plan, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_plan, common_plan_ec))};
            if (!common_plan_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure plan member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_plan = "plan";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_plan;
            ann_custom_GetPlan_Response.reset();
            CompleteMemberDetail detail_plan = TypeObjectUtils::build_complete_member_detail(name_plan, member_ann_builtin_plan, ann_custom_GetPlan_Response);
            CompleteStructMember member_plan = TypeObjectUtils::build_complete_struct_member(common_plan, detail_plan);
            TypeObjectUtils::add_complete_struct_member(member_seq_GetPlan_Response, member_plan);
        }
        CompleteStructType struct_type_GetPlan_Response = TypeObjectUtils::build_complete_struct_type(struct_flags_GetPlan_Response, header_GetPlan_Response, member_seq_GetPlan_Response);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_GetPlan_Response, type_name_GetPlan_Response.to_string(), type_ids_GetPlan_Response))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "nav_msgs::srv::GetPlan_Response already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace srv

} // namespace nav_msgs

