// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file camera_intrinsics_perspectiveTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#include "camera_intrinsics_perspectiveTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "camera_intrinsics_perspective.hpp"

#include "provizio/msg/camera_intrinsics_precise_model.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace provizio {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_camera_intrinsics_perspective_type_identifier(
        TypeIdentifierPair& type_ids_camera_intrinsics_perspective)
{

    ReturnCode_t return_code_camera_intrinsics_perspective {eprosima::fastdds::dds::RETCODE_OK};
    return_code_camera_intrinsics_perspective =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "provizio::msg::dds_::camera_intrinsics_perspective_", type_ids_camera_intrinsics_perspective);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_camera_intrinsics_perspective)
    {
        StructTypeFlag struct_flags_camera_intrinsics_perspective = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_camera_intrinsics_perspective = "provizio::msg::dds_::camera_intrinsics_perspective_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_camera_intrinsics_perspective;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_camera_intrinsics_perspective;
        CompleteTypeDetail detail_camera_intrinsics_perspective = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_camera_intrinsics_perspective, ann_custom_camera_intrinsics_perspective, type_name_camera_intrinsics_perspective.to_string());
        CompleteStructHeader header_camera_intrinsics_perspective;
        header_camera_intrinsics_perspective = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_camera_intrinsics_perspective);
        CompleteStructMemberSeq member_seq_camera_intrinsics_perspective;
        {
            TypeIdentifierPair type_ids_hfov;
            ReturnCode_t return_code_hfov {eprosima::fastdds::dds::RETCODE_OK};
            return_code_hfov =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_hfov);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_hfov)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "hfov Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_hfov = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_hfov = 0x00000000;
            bool common_hfov_ec {false};
            CommonStructMember common_hfov {TypeObjectUtils::build_common_struct_member(member_id_hfov, member_flags_hfov, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_hfov, common_hfov_ec))};
            if (!common_hfov_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure hfov member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_hfov = "hfov";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_hfov;
            ann_custom_camera_intrinsics_perspective.reset();
            CompleteMemberDetail detail_hfov = TypeObjectUtils::build_complete_member_detail(name_hfov, member_ann_builtin_hfov, ann_custom_camera_intrinsics_perspective);
            CompleteStructMember member_hfov = TypeObjectUtils::build_complete_struct_member(common_hfov, detail_hfov);
            TypeObjectUtils::add_complete_struct_member(member_seq_camera_intrinsics_perspective, member_hfov);
        }
        {
            TypeIdentifierPair type_ids_precise_model;
            ReturnCode_t return_code_precise_model {eprosima::fastdds::dds::RETCODE_OK};
            return_code_precise_model =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "provizio::msg::dds_::camera_intrinsics_precise_model_", type_ids_precise_model);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_precise_model)
            {
                ::provizio::msg::register_camera_intrinsics_precise_model_type_identifier(type_ids_precise_model);
            }
            StructMemberFlag member_flags_precise_model = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_precise_model = 0x00000001;
            bool common_precise_model_ec {false};
            CommonStructMember common_precise_model {TypeObjectUtils::build_common_struct_member(member_id_precise_model, member_flags_precise_model, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_precise_model, common_precise_model_ec))};
            if (!common_precise_model_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure precise_model member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_precise_model = "precise_model";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_precise_model;
            ann_custom_camera_intrinsics_perspective.reset();
            CompleteMemberDetail detail_precise_model = TypeObjectUtils::build_complete_member_detail(name_precise_model, member_ann_builtin_precise_model, ann_custom_camera_intrinsics_perspective);
            CompleteStructMember member_precise_model = TypeObjectUtils::build_complete_struct_member(common_precise_model, detail_precise_model);
            TypeObjectUtils::add_complete_struct_member(member_seq_camera_intrinsics_perspective, member_precise_model);
        }
        CompleteStructType struct_type_camera_intrinsics_perspective = TypeObjectUtils::build_complete_struct_type(struct_flags_camera_intrinsics_perspective, header_camera_intrinsics_perspective, member_seq_camera_intrinsics_perspective);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_camera_intrinsics_perspective, type_name_camera_intrinsics_perspective.to_string(), type_ids_camera_intrinsics_perspective))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "provizio::msg::camera_intrinsics_perspective already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace msg

} // namespace provizio

