// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file camera_intrinsics_orthographicTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#include "camera_intrinsics_orthographicTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "camera_intrinsics_orthographic.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace provizio {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_camera_intrinsics_orthographic_type_identifier(
        TypeIdentifierPair& type_ids_camera_intrinsics_orthographic)
{

    ReturnCode_t return_code_camera_intrinsics_orthographic {eprosima::fastdds::dds::RETCODE_OK};
    return_code_camera_intrinsics_orthographic =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "provizio::msg::dds_::camera_intrinsics_orthographic_", type_ids_camera_intrinsics_orthographic);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_camera_intrinsics_orthographic)
    {
        StructTypeFlag struct_flags_camera_intrinsics_orthographic = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_camera_intrinsics_orthographic = "provizio::msg::dds_::camera_intrinsics_orthographic_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_camera_intrinsics_orthographic;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_camera_intrinsics_orthographic;
        CompleteTypeDetail detail_camera_intrinsics_orthographic = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_camera_intrinsics_orthographic, ann_custom_camera_intrinsics_orthographic, type_name_camera_intrinsics_orthographic.to_string());
        CompleteStructHeader header_camera_intrinsics_orthographic;
        header_camera_intrinsics_orthographic = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_camera_intrinsics_orthographic);
        CompleteStructMemberSeq member_seq_camera_intrinsics_orthographic;
        {
            TypeIdentifierPair type_ids_width;
            ReturnCode_t return_code_width {eprosima::fastdds::dds::RETCODE_OK};
            return_code_width =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_width);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_width)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "width Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_width = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_width = 0x00000000;
            bool common_width_ec {false};
            CommonStructMember common_width {TypeObjectUtils::build_common_struct_member(member_id_width, member_flags_width, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_width, common_width_ec))};
            if (!common_width_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure width member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_width = "width";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_width;
            ann_custom_camera_intrinsics_orthographic.reset();
            CompleteMemberDetail detail_width = TypeObjectUtils::build_complete_member_detail(name_width, member_ann_builtin_width, ann_custom_camera_intrinsics_orthographic);
            CompleteStructMember member_width = TypeObjectUtils::build_complete_struct_member(common_width, detail_width);
            TypeObjectUtils::add_complete_struct_member(member_seq_camera_intrinsics_orthographic, member_width);
        }
        {
            TypeIdentifierPair type_ids_height;
            ReturnCode_t return_code_height {eprosima::fastdds::dds::RETCODE_OK};
            return_code_height =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_height);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_height)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "height Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_height = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_height = 0x00000001;
            bool common_height_ec {false};
            CommonStructMember common_height {TypeObjectUtils::build_common_struct_member(member_id_height, member_flags_height, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_height, common_height_ec))};
            if (!common_height_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure height member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_height = "height";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_height;
            ann_custom_camera_intrinsics_orthographic.reset();
            CompleteMemberDetail detail_height = TypeObjectUtils::build_complete_member_detail(name_height, member_ann_builtin_height, ann_custom_camera_intrinsics_orthographic);
            CompleteStructMember member_height = TypeObjectUtils::build_complete_struct_member(common_height, detail_height);
            TypeObjectUtils::add_complete_struct_member(member_seq_camera_intrinsics_orthographic, member_height);
        }
        CompleteStructType struct_type_camera_intrinsics_orthographic = TypeObjectUtils::build_complete_struct_type(struct_flags_camera_intrinsics_orthographic, header_camera_intrinsics_orthographic, member_seq_camera_intrinsics_orthographic);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_camera_intrinsics_orthographic, type_name_camera_intrinsics_orthographic.to_string(), type_ids_camera_intrinsics_orthographic))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "provizio::msg::camera_intrinsics_orthographic already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace msg

} // namespace provizio

