// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file radar_range.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "radar_range.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define builtin_interfaces_msg_Time_max_cdr_typesize 8ULL;

#define std_msgs_msg_Header_max_cdr_typesize 268ULL;
#define provizio_msg_set_radar_range_max_cdr_typesize 532ULL;
#define builtin_interfaces_msg_Time_max_key_cdr_typesize 0ULL;

#define std_msgs_msg_Header_max_key_cdr_typesize 0ULL;
#define provizio_msg_set_radar_range_max_key_cdr_typesize 0ULL;


provizio::msg::set_radar_range::set_radar_range()
{
    // std_msgs::msg::Header m_header

    // string m_serial_number
    m_serial_number ="";
    // provizio::msg::radar_range m_target_range
    m_target_range = provizio::msg::short_range;

}

provizio::msg::set_radar_range::~set_radar_range()
{



}

provizio::msg::set_radar_range::set_radar_range(
        const set_radar_range& x)
{
    m_header = x.m_header;
    m_serial_number = x.m_serial_number;
    m_target_range = x.m_target_range;
}

provizio::msg::set_radar_range::set_radar_range(
        set_radar_range&& x) noexcept 
{
    m_header = std::move(x.m_header);
    m_serial_number = std::move(x.m_serial_number);
    m_target_range = x.m_target_range;
}

provizio::msg::set_radar_range& provizio::msg::set_radar_range::operator =(
        const set_radar_range& x)
{

    m_header = x.m_header;
    m_serial_number = x.m_serial_number;
    m_target_range = x.m_target_range;

    return *this;
}

provizio::msg::set_radar_range& provizio::msg::set_radar_range::operator =(
        set_radar_range&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_serial_number = std::move(x.m_serial_number);
    m_target_range = x.m_target_range;

    return *this;
}

bool provizio::msg::set_radar_range::operator ==(
        const set_radar_range& x) const
{

    return (m_header == x.m_header && m_serial_number == x.m_serial_number && m_target_range == x.m_target_range);
}

bool provizio::msg::set_radar_range::operator !=(
        const set_radar_range& x) const
{
    return !(*this == x);
}

size_t provizio::msg::set_radar_range::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return provizio_msg_set_radar_range_max_cdr_typesize;
}

size_t provizio::msg::set_radar_range::getCdrSerializedSize(
        const provizio::msg::set_radar_range& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += std_msgs::msg::Header::getCdrSerializedSize(data.header(), current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.serial_number().size() + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void provizio::msg::set_radar_range::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_header;
    scdr << m_serial_number.c_str();
    scdr << (uint32_t)m_target_range;

}

void provizio::msg::set_radar_range::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_header;
    dcdr >> m_serial_number;
    {
        uint32_t enum_value = 0;
        dcdr >> enum_value;
        m_target_range = (provizio::msg::radar_range)enum_value;
    }

}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void provizio::msg::set_radar_range::header(
        const std_msgs::msg::Header& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void provizio::msg::set_radar_range::header(
        std_msgs::msg::Header&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const std_msgs::msg::Header& provizio::msg::set_radar_range::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
std_msgs::msg::Header& provizio::msg::set_radar_range::header()
{
    return m_header;
}
/*!
 * @brief This function copies the value in member serial_number
 * @param _serial_number New value to be copied in member serial_number
 */
void provizio::msg::set_radar_range::serial_number(
        const std::string& _serial_number)
{
    m_serial_number = _serial_number;
}

/*!
 * @brief This function moves the value in member serial_number
 * @param _serial_number New value to be moved in member serial_number
 */
void provizio::msg::set_radar_range::serial_number(
        std::string&& _serial_number)
{
    m_serial_number = std::move(_serial_number);
}

/*!
 * @brief This function returns a constant reference to member serial_number
 * @return Constant reference to member serial_number
 */
const std::string& provizio::msg::set_radar_range::serial_number() const
{
    return m_serial_number;
}

/*!
 * @brief This function returns a reference to member serial_number
 * @return Reference to member serial_number
 */
std::string& provizio::msg::set_radar_range::serial_number()
{
    return m_serial_number;
}
/*!
 * @brief This function sets a value in member target_range
 * @param _target_range New value for member target_range
 */
void provizio::msg::set_radar_range::target_range(
        provizio::msg::radar_range _target_range)
{
    m_target_range = _target_range;
}

/*!
 * @brief This function returns the value of member target_range
 * @return Value of member target_range
 */
provizio::msg::radar_range provizio::msg::set_radar_range::target_range() const
{
    return m_target_range;
}

/*!
 * @brief This function returns a reference to member target_range
 * @return Reference to member target_range
 */
provizio::msg::radar_range& provizio::msg::set_radar_range::target_range()
{
    return m_target_range;
}



size_t provizio::msg::set_radar_range::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return provizio_msg_set_radar_range_max_key_cdr_typesize;
}

bool provizio::msg::set_radar_range::isKeyDefined()
{
    return false;
}

void provizio::msg::set_radar_range::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}


