// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file NavSatFixTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#include "NavSatFixTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "NavSatFix.hpp"

#include "std_msgs/msg/Header.hpp"
#include "sensor_msgs/msg/NavSatStatus.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace sensor_msgs {
namespace msg {
void register_NavSatFix__double__9_type_identifier(
        TypeIdentifierPair& type_ids_NavSatFix__double__9)
{
    ReturnCode_t return_code_NavSatFix__double__9 {eprosima::fastdds::dds::RETCODE_OK};
    return_code_NavSatFix__double__9 =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "sensor_msgs::msg::NavSatFix__double__9", type_ids_NavSatFix__double__9);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_NavSatFix__double__9)
    {
        AliasTypeFlag alias_flags_NavSatFix__double__9 = 0;
        QualifiedTypeName type_name_NavSatFix__double__9 = "sensor_msgs::msg::NavSatFix__double__9";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_NavSatFix__double__9;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_NavSatFix__double__9;
        CompleteTypeDetail detail_NavSatFix__double__9 = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_NavSatFix__double__9, ann_custom_NavSatFix__double__9, type_name_NavSatFix__double__9.to_string());
        CompleteAliasHeader header_NavSatFix__double__9 = TypeObjectUtils::build_complete_alias_header(detail_NavSatFix__double__9);
        AliasMemberFlag related_flags_NavSatFix__double__9 = 0;
        return_code_NavSatFix__double__9 =
            eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
            "anonymous_array_double_9", type_ids_NavSatFix__double__9);

        if (eprosima::fastdds::dds::RETCODE_OK != return_code_NavSatFix__double__9)
        {
            return_code_NavSatFix__double__9 =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_NavSatFix__double__9);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_NavSatFix__double__9)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            bool element_identifier_anonymous_array_double_9_ec {false};
            TypeIdentifier* element_identifier_anonymous_array_double_9 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_NavSatFix__double__9, element_identifier_anonymous_array_double_9_ec))};
            if (!element_identifier_anonymous_array_double_9_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                return;
            }
            EquivalenceKind equiv_kind_anonymous_array_double_9 = EK_COMPLETE;
            if (TK_NONE == type_ids_NavSatFix__double__9.type_identifier2()._d())
            {
                equiv_kind_anonymous_array_double_9 = EK_BOTH;
            }
            CollectionElementFlag element_flags_anonymous_array_double_9 = 0;
            PlainCollectionHeader header_anonymous_array_double_9 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_9, element_flags_anonymous_array_double_9);
            {
                SBoundSeq array_bound_seq;
                    TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(9));

                PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_9, array_bound_seq,
                            eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_9));
                if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                        TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_9", type_ids_NavSatFix__double__9))
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "anonymous_array_double_9 already registered in TypeObjectRegistry for a different type.");
                }
            }
        }
        bool common_NavSatFix__double__9_ec {false};
        CommonAliasBody common_NavSatFix__double__9 {TypeObjectUtils::build_common_alias_body(related_flags_NavSatFix__double__9,
                TypeObjectUtils::retrieve_complete_type_identifier(type_ids_NavSatFix__double__9, common_NavSatFix__double__9_ec))};
        if (!common_NavSatFix__double__9_ec)
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "sensor_msgs::msg::NavSatFix__double__9 related TypeIdentifier inconsistent.");
            return;
        }
        eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_NavSatFix__double__9;
        ann_custom_NavSatFix__double__9.reset();
        CompleteAliasBody body_NavSatFix__double__9 = TypeObjectUtils::build_complete_alias_body(common_NavSatFix__double__9,
                member_ann_builtin_NavSatFix__double__9, ann_custom_NavSatFix__double__9);
        CompleteAliasType alias_type_NavSatFix__double__9 = TypeObjectUtils::build_complete_alias_type(alias_flags_NavSatFix__double__9,
                header_NavSatFix__double__9, body_NavSatFix__double__9);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_alias_type_object(alias_type_NavSatFix__double__9,
                    type_name_NavSatFix__double__9.to_string(), type_ids_NavSatFix__double__9))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "sensor_msgs::msg::NavSatFix__double__9 already registered in TypeObjectRegistry for a different type.");
        }
    }
}

namespace NavSatFix_Constants {
} // namespace NavSatFix_Constants
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_NavSatFix_type_identifier(
        TypeIdentifierPair& type_ids_NavSatFix)
{

    ReturnCode_t return_code_NavSatFix {eprosima::fastdds::dds::RETCODE_OK};
    return_code_NavSatFix =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "sensor_msgs::msg::dds_::NavSatFix_", type_ids_NavSatFix);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_NavSatFix)
    {
        StructTypeFlag struct_flags_NavSatFix = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_NavSatFix = "sensor_msgs::msg::dds_::NavSatFix_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_NavSatFix;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_NavSatFix;
        CompleteTypeDetail detail_NavSatFix = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_NavSatFix, ann_custom_NavSatFix, type_name_NavSatFix.to_string());
        CompleteStructHeader header_NavSatFix;
        header_NavSatFix = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_NavSatFix);
        CompleteStructMemberSeq member_seq_NavSatFix;
        {
            TypeIdentifierPair type_ids_header;
            ReturnCode_t return_code_header {eprosima::fastdds::dds::RETCODE_OK};
            return_code_header =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "std_msgs::msg::dds_::Header_", type_ids_header);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_header)
            {
                ::std_msgs::msg::register_Header_type_identifier(type_ids_header);
            }
            StructMemberFlag member_flags_header = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_header = 0x00000000;
            bool common_header_ec {false};
            CommonStructMember common_header {TypeObjectUtils::build_common_struct_member(member_id_header, member_flags_header, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_header, common_header_ec))};
            if (!common_header_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure header member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_header = "header";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_header;
            ann_custom_NavSatFix.reset();
            CompleteMemberDetail detail_header = TypeObjectUtils::build_complete_member_detail(name_header, member_ann_builtin_header, ann_custom_NavSatFix);
            CompleteStructMember member_header = TypeObjectUtils::build_complete_struct_member(common_header, detail_header);
            TypeObjectUtils::add_complete_struct_member(member_seq_NavSatFix, member_header);
        }
        {
            TypeIdentifierPair type_ids_status;
            ReturnCode_t return_code_status {eprosima::fastdds::dds::RETCODE_OK};
            return_code_status =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "sensor_msgs::msg::dds_::NavSatStatus_", type_ids_status);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_status)
            {
                ::sensor_msgs::msg::register_NavSatStatus_type_identifier(type_ids_status);
            }
            StructMemberFlag member_flags_status = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_status = 0x00000001;
            bool common_status_ec {false};
            CommonStructMember common_status {TypeObjectUtils::build_common_struct_member(member_id_status, member_flags_status, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_status, common_status_ec))};
            if (!common_status_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure status member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_status = "status";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_status;
            ann_custom_NavSatFix.reset();
            CompleteMemberDetail detail_status = TypeObjectUtils::build_complete_member_detail(name_status, member_ann_builtin_status, ann_custom_NavSatFix);
            CompleteStructMember member_status = TypeObjectUtils::build_complete_struct_member(common_status, detail_status);
            TypeObjectUtils::add_complete_struct_member(member_seq_NavSatFix, member_status);
        }
        {
            TypeIdentifierPair type_ids_latitude;
            ReturnCode_t return_code_latitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_latitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_latitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_latitude)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "latitude Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_latitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_latitude = 0x00000002;
            bool common_latitude_ec {false};
            CommonStructMember common_latitude {TypeObjectUtils::build_common_struct_member(member_id_latitude, member_flags_latitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_latitude, common_latitude_ec))};
            if (!common_latitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure latitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_latitude = "latitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_latitude;
            ann_custom_NavSatFix.reset();
            AppliedAnnotationSeq tmp_ann_custom_latitude;
            eprosima::fastcdr::optional<std::string> unit_latitude;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_latitude;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_latitude;
            eprosima::fastcdr::optional<std::string> hash_id_latitude;
            unit_latitude = "degrees";

            if (unit_latitude.has_value() || min_latitude.has_value() || max_latitude.has_value() || hash_id_latitude.has_value())
            {
                member_ann_builtin_latitude = TypeObjectUtils::build_applied_builtin_member_annotations(unit_latitude, min_latitude, max_latitude, hash_id_latitude);
            }
            if (!tmp_ann_custom_latitude.empty())
            {
                ann_custom_NavSatFix = tmp_ann_custom_latitude;
            }
            CompleteMemberDetail detail_latitude = TypeObjectUtils::build_complete_member_detail(name_latitude, member_ann_builtin_latitude, ann_custom_NavSatFix);
            CompleteStructMember member_latitude = TypeObjectUtils::build_complete_struct_member(common_latitude, detail_latitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_NavSatFix, member_latitude);
        }
        {
            TypeIdentifierPair type_ids_longitude;
            ReturnCode_t return_code_longitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_longitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_longitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_longitude)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "longitude Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_longitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_longitude = 0x00000003;
            bool common_longitude_ec {false};
            CommonStructMember common_longitude {TypeObjectUtils::build_common_struct_member(member_id_longitude, member_flags_longitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_longitude, common_longitude_ec))};
            if (!common_longitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure longitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_longitude = "longitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_longitude;
            ann_custom_NavSatFix.reset();
            AppliedAnnotationSeq tmp_ann_custom_longitude;
            eprosima::fastcdr::optional<std::string> unit_longitude;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_longitude;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_longitude;
            eprosima::fastcdr::optional<std::string> hash_id_longitude;
            unit_longitude = "degrees";

            if (unit_longitude.has_value() || min_longitude.has_value() || max_longitude.has_value() || hash_id_longitude.has_value())
            {
                member_ann_builtin_longitude = TypeObjectUtils::build_applied_builtin_member_annotations(unit_longitude, min_longitude, max_longitude, hash_id_longitude);
            }
            if (!tmp_ann_custom_longitude.empty())
            {
                ann_custom_NavSatFix = tmp_ann_custom_longitude;
            }
            CompleteMemberDetail detail_longitude = TypeObjectUtils::build_complete_member_detail(name_longitude, member_ann_builtin_longitude, ann_custom_NavSatFix);
            CompleteStructMember member_longitude = TypeObjectUtils::build_complete_struct_member(common_longitude, detail_longitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_NavSatFix, member_longitude);
        }
        {
            TypeIdentifierPair type_ids_altitude;
            ReturnCode_t return_code_altitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_altitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_altitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_altitude)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "altitude Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_altitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_altitude = 0x00000004;
            bool common_altitude_ec {false};
            CommonStructMember common_altitude {TypeObjectUtils::build_common_struct_member(member_id_altitude, member_flags_altitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_altitude, common_altitude_ec))};
            if (!common_altitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure altitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_altitude = "altitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_altitude;
            ann_custom_NavSatFix.reset();
            AppliedAnnotationSeq tmp_ann_custom_altitude;
            eprosima::fastcdr::optional<std::string> unit_altitude;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_altitude;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_altitude;
            eprosima::fastcdr::optional<std::string> hash_id_altitude;
            unit_altitude = "m";

            if (unit_altitude.has_value() || min_altitude.has_value() || max_altitude.has_value() || hash_id_altitude.has_value())
            {
                member_ann_builtin_altitude = TypeObjectUtils::build_applied_builtin_member_annotations(unit_altitude, min_altitude, max_altitude, hash_id_altitude);
            }
            if (!tmp_ann_custom_altitude.empty())
            {
                ann_custom_NavSatFix = tmp_ann_custom_altitude;
            }
            CompleteMemberDetail detail_altitude = TypeObjectUtils::build_complete_member_detail(name_altitude, member_ann_builtin_altitude, ann_custom_NavSatFix);
            CompleteStructMember member_altitude = TypeObjectUtils::build_complete_struct_member(common_altitude, detail_altitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_NavSatFix, member_altitude);
        }
        {
            TypeIdentifierPair type_ids_position_covariance;
            ReturnCode_t return_code_position_covariance {eprosima::fastdds::dds::RETCODE_OK};
            return_code_position_covariance =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "sensor_msgs::msg::NavSatFix__double__9", type_ids_position_covariance);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_position_covariance)
            {
                ::sensor_msgs::msg::register_NavSatFix__double__9_type_identifier(type_ids_position_covariance);
            }
            StructMemberFlag member_flags_position_covariance = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_position_covariance = 0x00000005;
            bool common_position_covariance_ec {false};
            CommonStructMember common_position_covariance {TypeObjectUtils::build_common_struct_member(member_id_position_covariance, member_flags_position_covariance, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_position_covariance, common_position_covariance_ec))};
            if (!common_position_covariance_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure position_covariance member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_position_covariance = "position_covariance";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_position_covariance;
            ann_custom_NavSatFix.reset();
            AppliedAnnotationSeq tmp_ann_custom_position_covariance;
            eprosima::fastcdr::optional<std::string> unit_position_covariance;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_position_covariance;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_position_covariance;
            eprosima::fastcdr::optional<std::string> hash_id_position_covariance;
            unit_position_covariance = "m^2";

            if (unit_position_covariance.has_value() || min_position_covariance.has_value() || max_position_covariance.has_value() || hash_id_position_covariance.has_value())
            {
                member_ann_builtin_position_covariance = TypeObjectUtils::build_applied_builtin_member_annotations(unit_position_covariance, min_position_covariance, max_position_covariance, hash_id_position_covariance);
            }
            if (!tmp_ann_custom_position_covariance.empty())
            {
                ann_custom_NavSatFix = tmp_ann_custom_position_covariance;
            }
            CompleteMemberDetail detail_position_covariance = TypeObjectUtils::build_complete_member_detail(name_position_covariance, member_ann_builtin_position_covariance, ann_custom_NavSatFix);
            CompleteStructMember member_position_covariance = TypeObjectUtils::build_complete_struct_member(common_position_covariance, detail_position_covariance);
            TypeObjectUtils::add_complete_struct_member(member_seq_NavSatFix, member_position_covariance);
        }
        {
            TypeIdentifierPair type_ids_position_covariance_type;
            ReturnCode_t return_code_position_covariance_type {eprosima::fastdds::dds::RETCODE_OK};
            return_code_position_covariance_type =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint8_t", type_ids_position_covariance_type);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_position_covariance_type)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "position_covariance_type Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_position_covariance_type = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_position_covariance_type = 0x00000006;
            bool common_position_covariance_type_ec {false};
            CommonStructMember common_position_covariance_type {TypeObjectUtils::build_common_struct_member(member_id_position_covariance_type, member_flags_position_covariance_type, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_position_covariance_type, common_position_covariance_type_ec))};
            if (!common_position_covariance_type_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure position_covariance_type member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_position_covariance_type = "position_covariance_type";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_position_covariance_type;
            ann_custom_NavSatFix.reset();
            CompleteMemberDetail detail_position_covariance_type = TypeObjectUtils::build_complete_member_detail(name_position_covariance_type, member_ann_builtin_position_covariance_type, ann_custom_NavSatFix);
            CompleteStructMember member_position_covariance_type = TypeObjectUtils::build_complete_struct_member(common_position_covariance_type, detail_position_covariance_type);
            TypeObjectUtils::add_complete_struct_member(member_seq_NavSatFix, member_position_covariance_type);
        }
        CompleteStructType struct_type_NavSatFix = TypeObjectUtils::build_complete_struct_type(struct_flags_NavSatFix, header_NavSatFix, member_seq_NavSatFix);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_NavSatFix, type_name_NavSatFix.to_string(), type_ids_NavSatFix))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "sensor_msgs::msg::NavSatFix already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace msg

} // namespace sensor_msgs

