// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file NavSatStatusPubSubTypes.hpp
 * This header file contains the declaration of the serialization functions.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */


#ifndef FAST_DDS_GENERATED__SENSOR_MSGS_MSG_NAVSATSTATUS_PUBSUBTYPES_HPP
#define FAST_DDS_GENERATED__SENSOR_MSGS_MSG_NAVSATSTATUS_PUBSUBTYPES_HPP

#include <mutex>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>
#include <fastdds/rtps/common/InstanceHandle.hpp>
#include <fastdds/rtps/common/SerializedPayload.hpp>
#include <fastdds/utils/md5.hpp>

#include "NavSatStatus.hpp"


#if !defined(FASTDDS_GEN_API_VER) || (FASTDDS_GEN_API_VER != 3)
#error \
    Generated NavSatStatus is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // FASTDDS_GEN_API_VER

namespace sensor_msgs {
namespace msg {
namespace NavSatStatus_Constants {
}  // namespace NavSatStatus_Constants

#ifndef SWIG
namespace detail {

template<typename Tag, typename Tag::type M>
struct NavSatStatus_rob
{
    friend constexpr typename Tag::type get(
            Tag)
    {
        return M;
    }

};

struct NavSatStatus_f
{
    typedef uint16_t NavSatStatus::* type;
    friend constexpr type get(
            NavSatStatus_f);
};

template struct NavSatStatus_rob<NavSatStatus_f, &NavSatStatus::m_service>;

template <typename T, typename Tag>
inline size_t constexpr NavSatStatus_offset_of()
{
    return ((::size_t) &reinterpret_cast<char const volatile&>((((T*)0)->*get(Tag()))));
}

} // namespace detail
#endif // ifndef SWIG


/*!
 * @brief This class represents the TopicDataType of the type NavSatStatus defined by the user in the IDL file.
 * @ingroup NavSatStatus
 */
class NavSatStatusPubSubType : public eprosima::fastdds::dds::TopicDataType
{
public:

    typedef ::sensor_msgs::msg::NavSatStatus type;

    eProsima_user_DllExport NavSatStatusPubSubType();

    eProsima_user_DllExport ~NavSatStatusPubSubType() override;

    eProsima_user_DllExport bool serialize(
            const void* const data,
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    eProsima_user_DllExport bool deserialize(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            void* data) override;

    eProsima_user_DllExport uint32_t calculate_serialized_size(
            const void* const data,
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) override;

    eProsima_user_DllExport bool compute_key(
            eprosima::fastdds::rtps::SerializedPayload_t& payload,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    eProsima_user_DllExport bool compute_key(
            const void* const data,
            eprosima::fastdds::rtps::InstanceHandle_t& ihandle,
            bool force_md5 = false) override;

    eProsima_user_DllExport void* create_data() override;

    eProsima_user_DllExport void delete_data(
            void* data) override;

    //Register TypeObject representation in Fast DDS TypeObjectRegistry
    eProsima_user_DllExport void register_type_object_representation() override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    eProsima_user_DllExport inline bool is_bounded() const override
    {
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

    eProsima_user_DllExport inline bool is_plain(
            eprosima::fastdds::dds::DataRepresentationId_t data_representation) const override
    {
        if (data_representation == eprosima::fastdds::dds::DataRepresentationId_t::XCDR2_DATA_REPRESENTATION)
        {
            return is_plain_xcdrv2_impl();
        }
        else
        {
            return is_plain_xcdrv1_impl();
        }
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    eProsima_user_DllExport inline bool construct_sample(
            void* memory) const override
    {
        new (memory) NavSatStatus();
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

private:


    static constexpr bool is_plain_xcdrv1_impl()
    {
        return 4ULL ==
               (detail::NavSatStatus_offset_of<NavSatStatus, detail::NavSatStatus_f>() +
               sizeof(uint16_t));
    }

    static constexpr bool is_plain_xcdrv2_impl()
    {
        return 4ULL ==
               (detail::NavSatStatus_offset_of<NavSatStatus, detail::NavSatStatus_f>() +
               sizeof(uint16_t));
    }

};

}  // namespace msg
}  // namespace sensor_msgs

#endif // FAST_DDS_GENERATED__SENSOR_MSGS_MSG_NAVSATSTATUS_PUBSUBTYPES_HPP

