// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file PointCloud.i
 * This header file contains the SWIG interface of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

%module(moduleimport="if __import__('os').name == 'nt': import win32api; win32api.LoadLibrary('PointCloud.dll')\nif __package__ or '.' in __name__:\n    from . import _PointCloudWrapper\nelse:\n    import _PointCloudWrapper") PointCloud

// If using windows in debug, it would try to use python_d, which would not be found.
%begin %{
#ifdef _MSC_VER
#define SWIG_PYTHON_INTERPRETER_NO_DEBUG
#endif
#include <exception>
%}

// SWIG helper modules
%include "stdint.i"
%include "std_array.i"
%include "std_map.i"
%include "std_string.i"
%include "std_vector.i"
%include "typemaps.i"

// Assignemt operators are ignored, as there is no such thing in Python.
// Trying to export them issues a warning
%ignore *::operator=;

// Macro declarations
// Any macro used on the Fast DDS header files will give an error if it is not redefined here
#define FASTDDS_EXPORTED_API
#define eProsima_user_DllExport

%include "geometry_msgs/msg/Point32.i"
%include "std_msgs/msg/Header.i"
%include "sensor_msgs/msg/ChannelFloat32.i"

%{
#include "PointCloud.hpp"
#include <fastdds/dds/core/LoanableSequence.hpp>
%}

%include <fastcdr/config.h>
%import(module="fastdds") "fastdds/dds/core/LoanableCollection.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableTypedCollection.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableSequence.hpp"

%define %traits_penumn(Type...)
  %fragment(SWIG_Traits_frag(Type),"header",
        fragment="StdTraits") {
namespace swig {
  template <> struct traits< Type > {
    typedef value_category category;
    static const char* type_name() { return  #Type; }
  };
}
}
%enddef

////////////////////////////////////////////////////////
// Binding for class sensor_msgs::msg::PointCloud
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore sensor_msgs::msg::PointCloud::PointCloud(sensor_msgs::msg::PointCloud&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore sensor_msgs::msg::PointCloud::header(std_msgs::msg::Header&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore sensor_msgs::msg::PointCloud::header();
%rename("%s") sensor_msgs::msg::PointCloud::header() const;



%ignore sensor_msgs::msg::PointCloud::points(std::vector<geometry_msgs::msg::Point32>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore sensor_msgs::msg::PointCloud::points() const;
%template(Point32_vector) std::vector<geometry_msgs::msg::Point32>;


%ignore sensor_msgs::msg::PointCloud::channels(std::vector<sensor_msgs::msg::ChannelFloat32>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore sensor_msgs::msg::PointCloud::channels() const;
%template(ChannelFloat32_vector) std::vector<sensor_msgs::msg::ChannelFloat32>;


%template(_PointCloudSeq) eprosima::fastdds::dds::LoanableTypedCollection<sensor_msgs::msg::PointCloud, std::false_type>;
%template(PointCloudSeq) eprosima::fastdds::dds::LoanableSequence<sensor_msgs::msg::PointCloud, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<sensor_msgs::msg::PointCloud, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const sensor_msgs::msg::PointCloud& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}


// Include the class interfaces
%include "PointCloud.hpp"

// Include the corresponding TopicDataType
%include "PointCloudPubSubTypes.i"

