// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file RegionOfInterest.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#ifndef FAST_DDS_GENERATED__SENSOR_MSGS_MSG_REGIONOFINTEREST_HPP
#define FAST_DDS_GENERATED__SENSOR_MSGS_MSG_REGIONOFINTEREST_HPP

#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(REGIONOFINTEREST_SOURCE)
#define REGIONOFINTEREST_DllAPI __declspec( dllexport )
#else
#define REGIONOFINTEREST_DllAPI __declspec( dllimport )
#endif // REGIONOFINTEREST_SOURCE
#else
#define REGIONOFINTEREST_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define REGIONOFINTEREST_DllAPI
#endif // _WIN32

namespace sensor_msgs {

namespace msg {

/*!
 * @brief This class represents the structure RegionOfInterest defined by the user in the IDL file.
 * @ingroup RegionOfInterest
 */
class RegionOfInterest
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport RegionOfInterest()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~RegionOfInterest()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object RegionOfInterest that will be copied.
     */
    eProsima_user_DllExport RegionOfInterest(
            const RegionOfInterest& x)
    {
                    m_x_offset = x.m_x_offset;

                    m_y_offset = x.m_y_offset;

                    m_height = x.m_height;

                    m_width = x.m_width;

                    m_do_rectify = x.m_do_rectify;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object RegionOfInterest that will be copied.
     */
    eProsima_user_DllExport RegionOfInterest(
            RegionOfInterest&& x) noexcept
    {
        m_x_offset = x.m_x_offset;
        m_y_offset = x.m_y_offset;
        m_height = x.m_height;
        m_width = x.m_width;
        m_do_rectify = x.m_do_rectify;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object RegionOfInterest that will be copied.
     */
    eProsima_user_DllExport RegionOfInterest& operator =(
            const RegionOfInterest& x)
    {

                    m_x_offset = x.m_x_offset;

                    m_y_offset = x.m_y_offset;

                    m_height = x.m_height;

                    m_width = x.m_width;

                    m_do_rectify = x.m_do_rectify;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object RegionOfInterest that will be copied.
     */
    eProsima_user_DllExport RegionOfInterest& operator =(
            RegionOfInterest&& x) noexcept
    {

        m_x_offset = x.m_x_offset;
        m_y_offset = x.m_y_offset;
        m_height = x.m_height;
        m_width = x.m_width;
        m_do_rectify = x.m_do_rectify;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x RegionOfInterest object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const RegionOfInterest& x) const
    {
        return (m_x_offset == x.m_x_offset &&
           m_y_offset == x.m_y_offset &&
           m_height == x.m_height &&
           m_width == x.m_width &&
           m_do_rectify == x.m_do_rectify);
    }

    /*!
     * @brief Comparison operator.
     * @param x RegionOfInterest object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const RegionOfInterest& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member x_offset
     * @param _x_offset New value for member x_offset
     */
    eProsima_user_DllExport void x_offset(
            uint32_t _x_offset)
    {
        m_x_offset = _x_offset;
    }

    /*!
     * @brief This function returns the value of member x_offset
     * @return Value of member x_offset
     */
    eProsima_user_DllExport uint32_t x_offset() const
    {
        return m_x_offset;
    }

    /*!
     * @brief This function returns a reference to member x_offset
     * @return Reference to member x_offset
     */
    eProsima_user_DllExport uint32_t& x_offset()
    {
        return m_x_offset;
    }


    /*!
     * @brief This function sets a value in member y_offset
     * @param _y_offset New value for member y_offset
     */
    eProsima_user_DllExport void y_offset(
            uint32_t _y_offset)
    {
        m_y_offset = _y_offset;
    }

    /*!
     * @brief This function returns the value of member y_offset
     * @return Value of member y_offset
     */
    eProsima_user_DllExport uint32_t y_offset() const
    {
        return m_y_offset;
    }

    /*!
     * @brief This function returns a reference to member y_offset
     * @return Reference to member y_offset
     */
    eProsima_user_DllExport uint32_t& y_offset()
    {
        return m_y_offset;
    }


    /*!
     * @brief This function sets a value in member height
     * @param _height New value for member height
     */
    eProsima_user_DllExport void height(
            uint32_t _height)
    {
        m_height = _height;
    }

    /*!
     * @brief This function returns the value of member height
     * @return Value of member height
     */
    eProsima_user_DllExport uint32_t height() const
    {
        return m_height;
    }

    /*!
     * @brief This function returns a reference to member height
     * @return Reference to member height
     */
    eProsima_user_DllExport uint32_t& height()
    {
        return m_height;
    }


    /*!
     * @brief This function sets a value in member width
     * @param _width New value for member width
     */
    eProsima_user_DllExport void width(
            uint32_t _width)
    {
        m_width = _width;
    }

    /*!
     * @brief This function returns the value of member width
     * @return Value of member width
     */
    eProsima_user_DllExport uint32_t width() const
    {
        return m_width;
    }

    /*!
     * @brief This function returns a reference to member width
     * @return Reference to member width
     */
    eProsima_user_DllExport uint32_t& width()
    {
        return m_width;
    }


    /*!
     * @brief This function sets a value in member do_rectify
     * @param _do_rectify New value for member do_rectify
     */
    eProsima_user_DllExport void do_rectify(
            bool _do_rectify)
    {
        m_do_rectify = _do_rectify;
    }

    /*!
     * @brief This function returns the value of member do_rectify
     * @return Value of member do_rectify
     */
    eProsima_user_DllExport bool do_rectify() const
    {
        return m_do_rectify;
    }

    /*!
     * @brief This function returns a reference to member do_rectify
     * @return Reference to member do_rectify
     */
    eProsima_user_DllExport bool& do_rectify()
    {
        return m_do_rectify;
    }



private:

    uint32_t m_x_offset{0};
    uint32_t m_y_offset{0};
    uint32_t m_height{0};
    uint32_t m_width{0};
    bool m_do_rectify{false};

};

} // namespace msg

} // namespace sensor_msgs

#endif // _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_REGIONOFINTEREST_HPP_


