// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TemperatureTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#include "TemperatureTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "Temperature.hpp"

#include "std_msgs/msg/Header.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace sensor_msgs {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Temperature_type_identifier(
        TypeIdentifierPair& type_ids_Temperature)
{

    ReturnCode_t return_code_Temperature {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Temperature =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "sensor_msgs::msg::dds_::Temperature_", type_ids_Temperature);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Temperature)
    {
        StructTypeFlag struct_flags_Temperature = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_Temperature = "sensor_msgs::msg::dds_::Temperature_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Temperature;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Temperature;
        CompleteTypeDetail detail_Temperature = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Temperature, ann_custom_Temperature, type_name_Temperature.to_string());
        CompleteStructHeader header_Temperature;
        header_Temperature = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Temperature);
        CompleteStructMemberSeq member_seq_Temperature;
        {
            TypeIdentifierPair type_ids_header;
            ReturnCode_t return_code_header {eprosima::fastdds::dds::RETCODE_OK};
            return_code_header =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "std_msgs::msg::dds_::Header_", type_ids_header);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_header)
            {
                ::std_msgs::msg::register_Header_type_identifier(type_ids_header);
            }
            StructMemberFlag member_flags_header = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_header = 0x00000000;
            bool common_header_ec {false};
            CommonStructMember common_header {TypeObjectUtils::build_common_struct_member(member_id_header, member_flags_header, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_header, common_header_ec))};
            if (!common_header_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure header member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_header = "header";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_header;
            ann_custom_Temperature.reset();
            CompleteMemberDetail detail_header = TypeObjectUtils::build_complete_member_detail(name_header, member_ann_builtin_header, ann_custom_Temperature);
            CompleteStructMember member_header = TypeObjectUtils::build_complete_struct_member(common_header, detail_header);
            TypeObjectUtils::add_complete_struct_member(member_seq_Temperature, member_header);
        }
        {
            TypeIdentifierPair type_ids_temperature;
            ReturnCode_t return_code_temperature {eprosima::fastdds::dds::RETCODE_OK};
            return_code_temperature =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_temperature);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_temperature)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "temperature Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_temperature = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_temperature = 0x00000001;
            bool common_temperature_ec {false};
            CommonStructMember common_temperature {TypeObjectUtils::build_common_struct_member(member_id_temperature, member_flags_temperature, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_temperature, common_temperature_ec))};
            if (!common_temperature_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure temperature member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_temperature = "temperature";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_temperature;
            ann_custom_Temperature.reset();
            CompleteMemberDetail detail_temperature = TypeObjectUtils::build_complete_member_detail(name_temperature, member_ann_builtin_temperature, ann_custom_Temperature);
            CompleteStructMember member_temperature = TypeObjectUtils::build_complete_struct_member(common_temperature, detail_temperature);
            TypeObjectUtils::add_complete_struct_member(member_seq_Temperature, member_temperature);
        }
        {
            TypeIdentifierPair type_ids_variance;
            ReturnCode_t return_code_variance {eprosima::fastdds::dds::RETCODE_OK};
            return_code_variance =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_variance);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_variance)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "variance Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_variance = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_variance = 0x00000002;
            bool common_variance_ec {false};
            CommonStructMember common_variance {TypeObjectUtils::build_common_struct_member(member_id_variance, member_flags_variance, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_variance, common_variance_ec))};
            if (!common_variance_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure variance member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_variance = "variance";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_variance;
            ann_custom_Temperature.reset();
            CompleteMemberDetail detail_variance = TypeObjectUtils::build_complete_member_detail(name_variance, member_ann_builtin_variance, ann_custom_Temperature);
            CompleteStructMember member_variance = TypeObjectUtils::build_complete_struct_member(common_variance, detail_variance);
            TypeObjectUtils::add_complete_struct_member(member_seq_Temperature, member_variance);
        }
        CompleteStructType struct_type_Temperature = TypeObjectUtils::build_complete_struct_type(struct_flags_Temperature, header_Temperature, member_seq_Temperature);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Temperature, type_name_Temperature.to_string(), type_ids_Temperature))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "sensor_msgs::msg::Temperature already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace msg

} // namespace sensor_msgs

