// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TimeReference.i
 * This header file contains the SWIG interface of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

%module(moduleimport="if __import__('os').name == 'nt': import win32api; win32api.LoadLibrary('TimeReference.dll')\nif __package__ or '.' in __name__:\n    from . import _TimeReferenceWrapper\nelse:\n    import _TimeReferenceWrapper") TimeReference

// If using windows in debug, it would try to use python_d, which would not be found.
%begin %{
#ifdef _MSC_VER
#define SWIG_PYTHON_INTERPRETER_NO_DEBUG
#endif
#include <exception>
%}

// SWIG helper modules
%include "stdint.i"
%include "std_array.i"
%include "std_map.i"
%include "std_string.i"
%include "std_vector.i"
%include "typemaps.i"

// Assignemt operators are ignored, as there is no such thing in Python.
// Trying to export them issues a warning
%ignore *::operator=;

// Macro declarations
// Any macro used on the Fast DDS header files will give an error if it is not redefined here
#define FASTDDS_EXPORTED_API
#define eProsima_user_DllExport

%include "builtin_interfaces/msg/Time.i"
%include "std_msgs/msg/Header.i"

%{
#include "TimeReference.hpp"
#include <fastdds/dds/core/LoanableSequence.hpp>
%}

%include <fastcdr/config.h>
%import(module="fastdds") "fastcdr/cdr/fixed_size_string.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableCollection.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableTypedCollection.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableSequence.hpp"

%define %traits_penumn(Type...)
  %fragment(SWIG_Traits_frag(Type),"header",
        fragment="StdTraits") {
namespace swig {
  template <> struct traits< Type > {
    typedef value_category category;
    static const char* type_name() { return  #Type; }
  };
}
}
%enddef

////////////////////////////////////////////////////////
// Binding for class sensor_msgs::msg::TimeReference
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore sensor_msgs::msg::TimeReference::TimeReference(sensor_msgs::msg::TimeReference&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore sensor_msgs::msg::TimeReference::header(std_msgs::msg::Header&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore sensor_msgs::msg::TimeReference::header();
%rename("%s") sensor_msgs::msg::TimeReference::header() const;



%ignore sensor_msgs::msg::TimeReference::time_ref(builtin_interfaces::msg::Time&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore sensor_msgs::msg::TimeReference::time_ref();
%rename("%s") sensor_msgs::msg::TimeReference::time_ref() const;



%ignore sensor_msgs::msg::TimeReference::source(std::string&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore sensor_msgs::msg::TimeReference::source();
%rename("%s") sensor_msgs::msg::TimeReference::source() const;



%template(_TimeReferenceSeq) eprosima::fastdds::dds::LoanableTypedCollection<sensor_msgs::msg::TimeReference, std::false_type>;
%template(TimeReferenceSeq) eprosima::fastdds::dds::LoanableSequence<sensor_msgs::msg::TimeReference, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<sensor_msgs::msg::TimeReference, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const sensor_msgs::msg::TimeReference& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}


// Include the class interfaces
%include "TimeReference.hpp"

// Include the corresponding TopicDataType
%include "TimeReferencePubSubTypes.i"

