// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file GetState.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "GetState.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

lifecycle_msgs::srv::GetState_Request::GetState_Request()
{
    // m_structure_needs_at_least_one_member com.eprosima.idl.parser.typecode.PrimitiveTypeCode@3243b914
    m_structure_needs_at_least_one_member = 0;

}

lifecycle_msgs::srv::GetState_Request::~GetState_Request()
{
}

lifecycle_msgs::srv::GetState_Request::GetState_Request(
        const GetState_Request& x)
{
    m_structure_needs_at_least_one_member = x.m_structure_needs_at_least_one_member;
}

lifecycle_msgs::srv::GetState_Request::GetState_Request(
        GetState_Request&& x) noexcept 
{
    m_structure_needs_at_least_one_member = x.m_structure_needs_at_least_one_member;
}

lifecycle_msgs::srv::GetState_Request& lifecycle_msgs::srv::GetState_Request::operator =(
        const GetState_Request& x)
{

    m_structure_needs_at_least_one_member = x.m_structure_needs_at_least_one_member;

    return *this;
}

lifecycle_msgs::srv::GetState_Request& lifecycle_msgs::srv::GetState_Request::operator =(
        GetState_Request&& x) noexcept
{

    m_structure_needs_at_least_one_member = x.m_structure_needs_at_least_one_member;

    return *this;
}

bool lifecycle_msgs::srv::GetState_Request::operator ==(
        const GetState_Request& x) const
{

    return (m_structure_needs_at_least_one_member == x.m_structure_needs_at_least_one_member);
}

bool lifecycle_msgs::srv::GetState_Request::operator !=(
        const GetState_Request& x) const
{
    return !(*this == x);
}

size_t lifecycle_msgs::srv::GetState_Request::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    return current_alignment - initial_alignment;
}

size_t lifecycle_msgs::srv::GetState_Request::getCdrSerializedSize(
        const lifecycle_msgs::srv::GetState_Request& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    return current_alignment - initial_alignment;
}

void lifecycle_msgs::srv::GetState_Request::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_structure_needs_at_least_one_member;

}

void lifecycle_msgs::srv::GetState_Request::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_structure_needs_at_least_one_member;
}

/*!
 * @brief This function sets a value in member structure_needs_at_least_one_member
 * @param _structure_needs_at_least_one_member New value for member structure_needs_at_least_one_member
 */
void lifecycle_msgs::srv::GetState_Request::structure_needs_at_least_one_member(
        uint8_t _structure_needs_at_least_one_member)
{
    m_structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
}

/*!
 * @brief This function returns the value of member structure_needs_at_least_one_member
 * @return Value of member structure_needs_at_least_one_member
 */
uint8_t lifecycle_msgs::srv::GetState_Request::structure_needs_at_least_one_member() const
{
    return m_structure_needs_at_least_one_member;
}

/*!
 * @brief This function returns a reference to member structure_needs_at_least_one_member
 * @return Reference to member structure_needs_at_least_one_member
 */
uint8_t& lifecycle_msgs::srv::GetState_Request::structure_needs_at_least_one_member()
{
    return m_structure_needs_at_least_one_member;
}


size_t lifecycle_msgs::srv::GetState_Request::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool lifecycle_msgs::srv::GetState_Request::isKeyDefined()
{
    return false;
}

void lifecycle_msgs::srv::GetState_Request::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
     
}

lifecycle_msgs::srv::GetState_Response::GetState_Response()
{
    // m_current_state com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@241e8ea6


}

lifecycle_msgs::srv::GetState_Response::~GetState_Response()
{
}

lifecycle_msgs::srv::GetState_Response::GetState_Response(
        const GetState_Response& x)
{
    m_current_state = x.m_current_state;
}

lifecycle_msgs::srv::GetState_Response::GetState_Response(
        GetState_Response&& x) noexcept 
{
    m_current_state = std::move(x.m_current_state);
}

lifecycle_msgs::srv::GetState_Response& lifecycle_msgs::srv::GetState_Response::operator =(
        const GetState_Response& x)
{

    m_current_state = x.m_current_state;

    return *this;
}

lifecycle_msgs::srv::GetState_Response& lifecycle_msgs::srv::GetState_Response::operator =(
        GetState_Response&& x) noexcept
{

    m_current_state = std::move(x.m_current_state);

    return *this;
}

bool lifecycle_msgs::srv::GetState_Response::operator ==(
        const GetState_Response& x) const
{

    return (m_current_state == x.m_current_state);
}

bool lifecycle_msgs::srv::GetState_Response::operator !=(
        const GetState_Response& x) const
{
    return !(*this == x);
}

size_t lifecycle_msgs::srv::GetState_Response::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += lifecycle_msgs::msg::State::getMaxCdrSerializedSize(current_alignment);

    return current_alignment - initial_alignment;
}

size_t lifecycle_msgs::srv::GetState_Response::getCdrSerializedSize(
        const lifecycle_msgs::srv::GetState_Response& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += lifecycle_msgs::msg::State::getCdrSerializedSize(data.current_state(), current_alignment);

    return current_alignment - initial_alignment;
}

void lifecycle_msgs::srv::GetState_Response::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_current_state;

}

void lifecycle_msgs::srv::GetState_Response::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_current_state;
}

/*!
 * @brief This function copies the value in member current_state
 * @param _current_state New value to be copied in member current_state
 */
void lifecycle_msgs::srv::GetState_Response::current_state(
        const lifecycle_msgs::msg::State& _current_state)
{
    m_current_state = _current_state;
}

/*!
 * @brief This function moves the value in member current_state
 * @param _current_state New value to be moved in member current_state
 */
void lifecycle_msgs::srv::GetState_Response::current_state(
        lifecycle_msgs::msg::State&& _current_state)
{
    m_current_state = std::move(_current_state);
}

/*!
 * @brief This function returns a constant reference to member current_state
 * @return Constant reference to member current_state
 */
const lifecycle_msgs::msg::State& lifecycle_msgs::srv::GetState_Response::current_state() const
{
    return m_current_state;
}

/*!
 * @brief This function returns a reference to member current_state
 * @return Reference to member current_state
 */
lifecycle_msgs::msg::State& lifecycle_msgs::srv::GetState_Response::current_state()
{
    return m_current_state;
}

size_t lifecycle_msgs::srv::GetState_Response::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool lifecycle_msgs::srv::GetState_Response::isKeyDefined()
{
    return false;
}

void lifecycle_msgs::srv::GetState_Response::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
     
}


