// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file set_radar_rangeCdrAux.hpp
 * This source file contains some definitions of CDR related functions.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#ifndef FAST_DDS_GENERATED__PROVIZIO_SRV_SET_RADAR_RANGECDRAUX_HPP
#define FAST_DDS_GENERATED__PROVIZIO_SRV_SET_RADAR_RANGECDRAUX_HPP

#include "set_radar_range.hpp"

constexpr uint32_t provizio_srv_set_radar_range_Request_max_cdr_typesize {532UL};
constexpr uint32_t provizio_srv_set_radar_range_Request_max_key_cdr_typesize {0UL};


constexpr uint32_t provizio_srv_set_radar_range_Response_max_cdr_typesize {800UL};
constexpr uint32_t provizio_srv_set_radar_range_Response_max_key_cdr_typesize {0UL};


namespace eprosima {
namespace fastcdr {

class Cdr;
class CdrSizeCalculator;

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const provizio::srv::set_radar_range_Request& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const provizio::srv::set_radar_range_Response& data);


} // namespace fastcdr
} // namespace eprosima

#endif // FAST_DDS_GENERATED__PROVIZIO_SRV_SET_RADAR_RANGECDRAUX_HPP

