// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file set_radar_range.i
 * This header file contains the SWIG interface of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

%module set_radar_range

// SWIG helper modules
%include "stdint.i"
%include "std_array.i"
%include "std_map.i"
%include "std_string.i"
%include "std_vector.i"
%include "typemaps.i"

// Assignemt operators are ignored, as there is no such thing in Python.
// Trying to export them issues a warning
%ignore *::operator=;

// Macro declarations
// Any macro used on the Fast DDS header files will give an error if it is not redefined here
#define RTPS_DllAPI
#define eProsima_user_DllExport

%include "std_msgs/msg/Header.i"
%include "provizio/msg/radar_range.i"

%{
#include "set_radar_range.h"

#include <fastdds/dds/core/LoanableSequence.hpp>
%}

%import(module="fastdds") "fastdds/dds/core/LoanableCollection.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableTypedCollection.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableSequence.hpp"

////////////////////////////////////////////////////////
// Binding for class provizio::srv::set_radar_range_Request
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore provizio::srv::set_radar_range_Request::set_radar_range_Request(provizio::srv::set_radar_range_Request&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore provizio::srv::set_radar_range_Request::header(std_msgs::msg::Header&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore provizio::srv::set_radar_range_Request::header();
%rename("%s") provizio::srv::set_radar_range_Request::header() const;


%ignore provizio::srv::set_radar_range_Request::serial_number(std::string&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore provizio::srv::set_radar_range_Request::serial_number();
%rename("%s") provizio::srv::set_radar_range_Request::serial_number() const;


%ignore provizio::srv::set_radar_range_Request::target_range(provizio::msg::radar_range&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore provizio::srv::set_radar_range_Request::target_range();
%rename("%s") provizio::srv::set_radar_range_Request::target_range() const;



%template(_set_radar_range_RequestSeq) eprosima::fastdds::dds::LoanableTypedCollection<provizio::srv::set_radar_range_Request, std::false_type>;
%template(set_radar_range_RequestSeq) eprosima::fastdds::dds::LoanableSequence<provizio::srv::set_radar_range_Request, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<provizio::srv::set_radar_range_Request, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const provizio::srv::set_radar_range_Request& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class provizio::srv::set_radar_range_Response
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore provizio::srv::set_radar_range_Response::set_radar_range_Response(provizio::srv::set_radar_range_Response&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore provizio::srv::set_radar_range_Response::header(std_msgs::msg::Header&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore provizio::srv::set_radar_range_Response::header();
%rename("%s") provizio::srv::set_radar_range_Response::header() const;


%ignore provizio::srv::set_radar_range_Response::success(bool&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore provizio::srv::set_radar_range_Response::success();
%rename("%s") provizio::srv::set_radar_range_Response::success() const;


%ignore provizio::srv::set_radar_range_Response::error_message(std::string&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore provizio::srv::set_radar_range_Response::error_message();
%rename("%s") provizio::srv::set_radar_range_Response::error_message() const;


%ignore provizio::srv::set_radar_range_Response::serial_number(std::string&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore provizio::srv::set_radar_range_Response::serial_number();
%rename("%s") provizio::srv::set_radar_range_Response::serial_number() const;


%ignore provizio::srv::set_radar_range_Response::supported_ranges(std::vector<provizio::msg::radar_range>&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore provizio::srv::set_radar_range_Response::supported_ranges() const;
%extend std::vector<provizio::msg::radar_range>
{
    const provizio::msg::radar_range* get_buffer() const
    {
        return self->data();
    }
}

%template(
provizio_msg_radar_range_vector
) std::vector<provizio::msg::radar_range>;

%ignore provizio::srv::set_radar_range_Response::current_range(provizio::msg::radar_range&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore provizio::srv::set_radar_range_Response::current_range();
%rename("%s") provizio::srv::set_radar_range_Response::current_range() const;



%template(_set_radar_range_ResponseSeq) eprosima::fastdds::dds::LoanableTypedCollection<provizio::srv::set_radar_range_Response, std::false_type>;
%template(set_radar_range_ResponseSeq) eprosima::fastdds::dds::LoanableSequence<provizio::srv::set_radar_range_Response, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<provizio::srv::set_radar_range_Response, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const provizio::srv::set_radar_range_Response& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}




// Include the class interfaces
%include "set_radar_range.h"

// Include the corresponding TopicDataType
%include "set_radar_rangePubSubTypes.i"

