// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file set_radar_range.i
 * This header file contains the SWIG interface of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

%module(moduleimport="if __import__('os').name == 'nt': import win32api; win32api.LoadLibrary('set_radar_range.dll')\nif __package__ or '.' in __name__:\n    from . import _set_radar_rangeWrapper\nelse:\n    import _set_radar_rangeWrapper") set_radar_range

// If using windows in debug, it would try to use python_d, which would not be found.
%begin %{
#ifdef _MSC_VER
#define SWIG_PYTHON_INTERPRETER_NO_DEBUG
#endif
#include <exception>
%}

// SWIG helper modules
%include "stdint.i"
%include "std_array.i"
%include "std_map.i"
%include "std_string.i"
%include "std_vector.i"
%include "typemaps.i"

// Assignemt operators are ignored, as there is no such thing in Python.
// Trying to export them issues a warning
%ignore *::operator=;

// Macro declarations
// Any macro used on the Fast DDS header files will give an error if it is not redefined here
#define FASTDDS_EXPORTED_API
#define eProsima_user_DllExport

%include "std_msgs/msg/Header.i"

%{
#include "set_radar_range.hpp"
#include <fastdds/dds/core/LoanableSequence.hpp>
%}

%include <fastcdr/config.h>
%import(module="fastdds") "fastcdr/cdr/fixed_size_string.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableCollection.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableTypedCollection.hpp"
%import(module="fastdds") "fastdds/dds/core/LoanableSequence.hpp"

%define %traits_penumn(Type...)
  %fragment(SWIG_Traits_frag(Type),"header",
        fragment="StdTraits") {
namespace swig {
  template <> struct traits< Type > {
    typedef value_category category;
    static const char* type_name() { return  #Type; }
  };
}
}
%enddef

////////////////////////////////////////////////////////
// Binding for class provizio::srv::set_radar_range_Request
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore provizio::srv::set_radar_range_Request::set_radar_range_Request(provizio::srv::set_radar_range_Request&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore provizio::srv::set_radar_range_Request::header(std_msgs::msg::Header&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore provizio::srv::set_radar_range_Request::header();
%rename("%s") provizio::srv::set_radar_range_Request::header() const;



%ignore provizio::srv::set_radar_range_Request::serial_number(std::string&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore provizio::srv::set_radar_range_Request::serial_number();
%rename("%s") provizio::srv::set_radar_range_Request::serial_number() const;



%ignore provizio::srv::set_radar_range_Request::target_range(uint32_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore provizio::srv::set_radar_range_Request::target_range();
%rename("%s") provizio::srv::set_radar_range_Request::target_range() const;



%template(_set_radar_range_RequestSeq) eprosima::fastdds::dds::LoanableTypedCollection<provizio::srv::set_radar_range_Request, std::false_type>;
%template(set_radar_range_RequestSeq) eprosima::fastdds::dds::LoanableSequence<provizio::srv::set_radar_range_Request, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<provizio::srv::set_radar_range_Request, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const provizio::srv::set_radar_range_Request& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}

////////////////////////////////////////////////////////
// Binding for class provizio::srv::set_radar_range_Response
////////////////////////////////////////////////////////

// Ignore overloaded methods that have no application on Python
// Otherwise they will issue a warning
%ignore provizio::srv::set_radar_range_Response::set_radar_range_Response(provizio::srv::set_radar_range_Response&&);

// Overloaded getter methods shadow each other and are equivalent in python
// Avoid a warning ignoring all but one
%ignore provizio::srv::set_radar_range_Response::header(std_msgs::msg::Header&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore provizio::srv::set_radar_range_Response::header();
%rename("%s") provizio::srv::set_radar_range_Response::header() const;



%ignore provizio::srv::set_radar_range_Response::success(bool&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore provizio::srv::set_radar_range_Response::success();
%rename("%s") provizio::srv::set_radar_range_Response::success() const;



%ignore provizio::srv::set_radar_range_Response::error_message(std::string&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore provizio::srv::set_radar_range_Response::error_message();
%rename("%s") provizio::srv::set_radar_range_Response::error_message() const;



%ignore provizio::srv::set_radar_range_Response::serial_number(std::string&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore provizio::srv::set_radar_range_Response::serial_number();
%rename("%s") provizio::srv::set_radar_range_Response::serial_number() const;



%ignore provizio::srv::set_radar_range_Response::supported_ranges(std::vector<uint32_t>&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore provizio::srv::set_radar_range_Response::supported_ranges() const;
%extend std::vector<uint32_t>
{
    const uint32_t* get_buffer() const
    {
        return self->data();
    }
}

%template(uint32_t_vector) std::vector<uint32_t>;


%ignore provizio::srv::set_radar_range_Response::current_range(uint32_t&&);


// Overloaded getter methods shadow each other and are equivalent in python
// Const accesors produced constant enums instead of arrays/dictionaries when used
// We ignore them to prevent this
%ignore provizio::srv::set_radar_range_Response::current_range();
%rename("%s") provizio::srv::set_radar_range_Response::current_range() const;



%template(_set_radar_range_ResponseSeq) eprosima::fastdds::dds::LoanableTypedCollection<provizio::srv::set_radar_range_Response, std::false_type>;
%template(set_radar_range_ResponseSeq) eprosima::fastdds::dds::LoanableSequence<provizio::srv::set_radar_range_Response, std::false_type>;
%extend eprosima::fastdds::dds::LoanableSequence<provizio::srv::set_radar_range_Response, std::false_type>
{
    size_t __len__() const
    {
        return self->length();
    }

    const provizio::srv::set_radar_range_Response& __getitem__(size_t i) const
    {
        return (*self)[i];
    }
}


// Include the class interfaces
%include "set_radar_range.hpp"

// Include the corresponding TopicDataType
%include "set_radar_rangePubSubTypes.i"

