name: Generate and update types wrapper code

on:
  push:
    branches-ignore:
      - master
      - develop

jobs:
  codegen:
    name: Generate and update types wrapper code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            repository: eProsima/Fast-DDS-Gen
            ref: v3.0.1
            path: build/Fast-DDS-Gen
            submodules: recursive
      - run: .github/workflows/sudo.sh .github/workflows/install_dependencies.sh
      - run: cd build/Fast-DDS-Gen && ./gradlew build -x test && ../../.github/workflows/sudo.sh ./gradlew install
      - run: cd build && cmake ..
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Types Wrapper Code Generated
